import type { M41bGovernedSource } from "./model";

const common = {
  reviewedAt: "2026-10-01T12:00:00.000Z",
  expiresAt: "2027-01-31T23:59:59.000Z",
  applicableLimits: ["Synthetic prototype guidance only", "Human accountability remains controlling"],
  missingEvidence: [],
  state: "current" as const,
  confidence: 0.96,
  uncertainty: null,
  sensitivity: "internal" as const,
  minimumTier: "T4" as const,
  evidenceClass: "synthetic_demo" as const,
};

export const M41B_SOURCE_REGISTER: readonly M41bGovernedSource[] = Object.freeze([
  {
    ...common,
    id: "M41B-SRC-DAILY-OPS",
    title: "Daily priority and shift-control standard",
    sourceSystem: "AMOS-OPS Workflow Registry",
    sourceType: "workflow",
    version: "1.0",
    ownerRole: "administrator",
    effectiveAt: "2026-10-01T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:50:00.000Z",
    divisions: ["eo", "gad", "bhc", "gro"],
    cadences: ["daily"],
    materialDomain: "operational",
    recordIds: ["SYNTH-WORKFLOW-DAILY-001"],
  },
  {
    ...common,
    id: "M41B-SRC-WEEKLY-REVIEW",
    title: "Weekly caseload and operating-review standard",
    sourceSystem: "AMOS-OPS Operating Calendar",
    sourceType: "commitment",
    version: "1.0",
    ownerRole: "managing-director",
    effectiveAt: "2026-10-01T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:45:00.000Z",
    divisions: ["eo", "gad", "bhc", "gro"],
    cadences: ["weekly"],
    materialDomain: "supervisory",
    recordIds: ["SYNTH-COMMITMENT-WEEKLY-001"],
  },
  {
    ...common,
    id: "M41B-SRC-MEETING-ACTION",
    title: "Governed operating-meeting action register",
    sourceSystem: "AMOS-OPS Meeting and Commitment Registry",
    sourceType: "meeting_action",
    version: "1.0",
    ownerRole: "administrator",
    effectiveAt: "2026-10-01T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:42:00.000Z",
    divisions: ["eo", "gad", "bhc", "gro"],
    cadences: ["daily", "weekly"],
    materialDomain: "operational",
    recordIds: ["SYNTH-MEETING-ACTION-001"],
  },
  {
    ...common,
    id: "M41B-SRC-MONTHLY-PERFORMANCE",
    title: "Monthly performance-review standard",
    sourceSystem: "AMOS-OPS MGMA and Performance Registry",
    sourceType: "performance_record",
    version: "1.0",
    ownerRole: "managing-director",
    effectiveAt: "2026-10-01T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:40:00.000Z",
    divisions: ["eo", "gad", "bhc", "gro"],
    cadences: ["monthly"],
    materialDomain: "financial",
    recordIds: ["SYNTH-PERFORMANCE-MONTHLY-001"],
  },
  {
    ...common,
    id: "M41B-SRC-QUARTERLY-COMPLIANCE",
    title: "Quarterly strategy and compliance-review standard",
    sourceSystem: "AMOS-OPS Compliance Registry",
    sourceType: "policy",
    version: "1.0",
    ownerRole: "hr-compliance-officer",
    effectiveAt: "2026-10-01T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:35:00.000Z",
    divisions: ["eo", "gad", "bhc", "gro"],
    cadences: ["quarterly"],
    materialDomain: "regulatory",
    recordIds: ["SYNTH-COMPLIANCE-QUARTERLY-001"],
  },
  {
    ...common,
    id: "M41B-SRC-ANNUAL-PLANNING",
    title: "Annual planning and reauthorization standard",
    sourceSystem: "AMOS-OPS Governance Registry",
    sourceType: "policy",
    version: "1.0",
    ownerRole: "managing-director",
    effectiveAt: "2026-10-01T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:30:00.000Z",
    divisions: ["eo", "gad", "bhc", "gro"],
    cadences: ["annual"],
    materialDomain: "legal",
    recordIds: ["SYNTH-GOVERNANCE-ANNUAL-001"],
  },
  {
    ...common,
    id: "M41B-SRC-EXEC-ALERT",
    title: "Executive unresolved compliance alert",
    sourceSystem: "AMOS-OPS M4.1A Decision Intelligence",
    sourceType: "dashboard_alert",
    version: "1.0",
    ownerRole: "administrator",
    effectiveAt: "2026-10-14T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:55:00.000Z",
    divisions: ["eo"],
    minimumTier: "T1",
    cadences: ["daily", "weekly"],
    materialDomain: "regulatory",
    recordIds: ["SYNTH-M41A-ALERT-ENTERPRISE-ENTERPRISE-MGMA-013"],
  },
  {
    ...common,
    id: "M41B-SRC-BHC-AUDIT",
    title: "BHC controlled audit finding",
    sourceSystem: "AMOS-OPS Compliance and Audit",
    sourceType: "audit_finding",
    version: "1.0",
    ownerRole: "bhc-director",
    effectiveAt: "2026-10-14T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:25:00.000Z",
    sensitivity: "clinical",
    divisions: ["bhc"],
    cadences: ["daily", "weekly", "monthly"],
    materialDomain: "clinical",
    recordIds: ["SYNTH-BHC-AUDIT-001"],
  },
  {
    ...common,
    id: "M41B-SRC-GRO-SHIFT",
    title: "GRO shift exception and supervisor handoff",
    sourceSystem: "AMOS-OPS GRO Operations",
    sourceType: "exception",
    version: "1.0",
    ownerRole: "program-director",
    effectiveAt: "2026-10-15T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:58:00.000Z",
    sensitivity: "clinical",
    divisions: ["gro"],
    cadences: ["daily", "weekly"],
    materialDomain: "supervisory",
    recordIds: ["SYNTH-GRO-SHIFT-EXCEPTION-001"],
  },
  {
    ...common,
    id: "M41B-SRC-FINANCE-CONFLICT",
    title: "Contradictory revenue variance sources",
    sourceSystem: "AMOS-OPS Revenue Reconciliation",
    sourceType: "exception",
    version: "1.0",
    ownerRole: "revenue-cycle-manager",
    effectiveAt: "2026-10-15T00:00:00.000Z",
    refreshedAt: "2026-10-15T07:20:00.000Z",
    state: "contradictory",
    confidence: null,
    uncertainty: "Two governed source reports disagree; no preferred value is selected.",
    sensitivity: "finance",
    divisions: ["eo"],
    minimumTier: "T3",
    cadences: ["daily", "monthly"],
    materialDomain: "financial",
    recordIds: ["SYNTH-REVENUE-REPORT-A", "SYNTH-REVENUE-REPORT-B"],
  },
  {
    ...common,
    id: "M41B-SRC-CLINICAL-MISSING",
    title: "Unavailable clinical evidence scenario",
    sourceSystem: "AMOS-OPS Clinical Workflow",
    sourceType: "exception",
    version: "1.0",
    ownerRole: "clinical-director",
    effectiveAt: "2026-10-15T00:00:00.000Z",
    refreshedAt: null,
    state: "missing",
    confidence: null,
    uncertainty: "Required governed clinical evidence is unavailable.",
    missingEvidence: ["Current authorized clinical assessment"],
    sensitivity: "clinical",
    divisions: ["bhc"],
    cadences: ["daily"],
    materialDomain: "clinical",
    recordIds: [],
  },
  {
    ...common,
    id: "M41B-SRC-PERSONNEL-STALE",
    title: "Stale workforce access-review finding",
    sourceSystem: "AMOS-OPS Workforce Management",
    sourceType: "audit_finding",
    version: "1.0",
    ownerRole: "hr-director",
    effectiveAt: "2026-07-01T00:00:00.000Z",
    refreshedAt: "2026-07-01T12:00:00.000Z",
    state: "stale",
    confidence: 0.42,
    uncertainty: "The source is outside its approved freshness window.",
    sensitivity: "personnel",
    divisions: ["eo"],
    minimumTier: "T3",
    cadences: ["daily", "quarterly"],
    materialDomain: "personnel",
    recordIds: ["SYNTH-WORKFORCE-ACCESS-REVIEW-001"],
  },
]);

export function m41bSourceById(id: string): M41bGovernedSource {
  const source = M41B_SOURCE_REGISTER.find((candidate) => candidate.id === id);
  if (!source) throw new Error(`M41B_SOURCE_NOT_FOUND:${id}`);
  return source;
}
