CREATE TABLE `agent_personas` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`code` text NOT NULL,
	`description` text NOT NULL,
	`status` text DEFAULT 'inactive' NOT NULL,
	`wave` text DEFAULT 'wave3' NOT NULL,
	`category` text NOT NULL,
	`permissions` text,
	`outputs` text,
	`activated_at` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `assessment_domains` (
	`id` text PRIMARY KEY NOT NULL,
	`assessment_id` text NOT NULL,
	`domain_number` integer NOT NULL,
	`domain_name` text NOT NULL,
	`score` integer,
	`score_label` text,
	`strengths` text,
	`needs` text,
	`observations` text,
	`clinical_notes` text,
	`intervention_needed` integer DEFAULT false NOT NULL,
	`intervention_description` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `assessments` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`mrn` text NOT NULL,
	`youth_name` text NOT NULL,
	`assessment_type` text DEFAULT 'intake' NOT NULL,
	`assessment_date` text NOT NULL,
	`completed_by` text NOT NULL,
	`completed_by_id` text,
	`clinician_name` text,
	`clinician_id` text,
	`supervisor_name` text,
	`supervisor_id` text,
	`presenting_problems` text,
	`psychiatric_history` text,
	`substance_use_history` text,
	`trauma_history` text,
	`medical_history` text,
	`family_history` text,
	`educational_history` text,
	`cans_completed` integer DEFAULT false NOT NULL,
	`cans_total_score` integer,
	`cans_risk_level` text,
	`loc_determined` integer DEFAULT false NOT NULL,
	`loc_level` text DEFAULT 'not_determined',
	`loc_decision_matrix_json` text,
	`loc_clinical_rationale` text,
	`loc_approved_by` text,
	`loc_approved_at` text,
	`risk_suicide` text,
	`risk_self_harm` text,
	`risk_aggression` text,
	`risk_elopement` text,
	`risk_substance_use` text,
	`risk_vulnerability` text,
	`overall_risk_level` text,
	`safety_plan_required` integer DEFAULT false NOT NULL,
	`safety_plan_completed` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`reviewed_by` text,
	`reviewed_at` text,
	`approved_by` text,
	`approved_at` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text,
	`updated_by` text
);
--> statement-breakpoint
CREATE TABLE `audit_logs` (
	`id` text PRIMARY KEY NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` text NOT NULL,
	`action` text NOT NULL,
	`performed_by` text NOT NULL,
	`performed_at` text,
	`old_values` text,
	`new_values` text,
	`ip_address` text,
	`user_agent` text
);
--> statement-breakpoint
CREATE TABLE `audits_qa` (
	`id` text PRIMARY KEY NOT NULL,
	`audit_number` text NOT NULL,
	`title` text NOT NULL,
	`audit_type` text NOT NULL,
	`scope` text NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`assigned_auditor_id` text,
	`department` text,
	`findings_json` text DEFAULT '[]',
	`score` integer,
	`started_at` text,
	`completed_at` text,
	`due_date` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `audits_qa_audit_number_unique` ON `audits_qa` (`audit_number`);--> statement-breakpoint
CREATE TABLE `authorizations` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`payer_name` text NOT NULL,
	`policy_number` text,
	`stage` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`readiness_clinical_docs` integer DEFAULT false NOT NULL,
	`readiness_assessment_current` integer DEFAULT false NOT NULL,
	`readiness_loc_supported` integer DEFAULT false NOT NULL,
	`readiness_treatment_plan` integer DEFAULT false NOT NULL,
	`readiness_progress_notes` integer DEFAULT false NOT NULL,
	`readiness_medical_necessity` integer DEFAULT false NOT NULL,
	`readiness_utilization_review` integer DEFAULT false NOT NULL,
	`readiness_guardian_consent` integer DEFAULT false NOT NULL,
	`readiness_ub04_clean` integer DEFAULT false NOT NULL,
	`readiness_excluded_services` integer DEFAULT false NOT NULL,
	`readiness_met_at` text,
	`submission_date` text,
	`submitted_by` text,
	`submission_method` text,
	`submission_reference` text,
	`authorization_number` text,
	`approved_units` integer,
	`approved_from_date` text,
	`approved_to_date` text,
	`approved_level_of_care` text,
	`denial_reason` text,
	`appeal_date` text,
	`appeal_status` text,
	`reauth_due_date` text,
	`reauth_submitted_at` text,
	`reauth_status` text DEFAULT 'not_due',
	`days_until_expiration` integer,
	`retrospective_review_date` text,
	`retrospective_findings` text,
	`retrospective_actions` text,
	`billing_excluded_services` text,
	`exclusion_controls_applied` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `bed_census` (
	`id` text PRIMARY KEY NOT NULL,
	`room_number` text NOT NULL,
	`bed_letter` text NOT NULL,
	`bed_name` text NOT NULL,
	`is_occupied` integer DEFAULT false NOT NULL,
	`youth_id` text,
	`youth_name` text,
	`mrn` text,
	`assigned_date` text,
	`is_accessible` integer DEFAULT false NOT NULL,
	`is_observation` integer DEFAULT false NOT NULL,
	`is_quiet` integer DEFAULT false NOT NULL,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `bed_census_v2` (
	`id` text PRIMARY KEY NOT NULL,
	`facility_id` text NOT NULL,
	`room_id` text NOT NULL,
	`bed_number` text NOT NULL,
	`bed_label` text NOT NULL,
	`is_occupied` integer DEFAULT false NOT NULL,
	`youth_id` text,
	`youth_name` text,
	`mrn` text,
	`assigned_date` text,
	`expected_discharge_date` text,
	`is_accessible` integer DEFAULT false NOT NULL,
	`is_observation` integer DEFAULT false NOT NULL,
	`is_quiet` integer DEFAULT false NOT NULL,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `behavioral_observations` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`observation_date` text NOT NULL,
	`observed_by` text NOT NULL,
	`behavior_type` text NOT NULL,
	`frequency` text,
	`intensity` text,
	`duration` text,
	`triggers` text,
	`antecedents` text,
	`intervention_used` text,
	`intervention_effective` integer,
	`prn_administered` integer DEFAULT false NOT NULL,
	`prn_details` text,
	`outcome` text,
	`follow_up_needed` integer DEFAULT false NOT NULL,
	`follow_up_actions` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `bhc_department_metrics` (
	`id` text PRIMARY KEY NOT NULL,
	`department` text NOT NULL,
	`metric_date` text NOT NULL,
	`active_cases` integer DEFAULT 0 NOT NULL,
	`new_intakes` integer DEFAULT 0 NOT NULL,
	`discharges` integer DEFAULT 0 NOT NULL,
	`transfers_in` integer DEFAULT 0 NOT NULL,
	`transfers_out` integer DEFAULT 0 NOT NULL,
	`avg_length_of_stay_days` integer,
	`plans_overdue` integer DEFAULT 0 NOT NULL,
	`encounters_this_week` integer DEFAULT 0 NOT NULL,
	`cans_completion_rate` integer,
	`satisfaction_score` integer,
	`staff_count` integer DEFAULT 0 NOT NULL,
	`open_positions` integer DEFAULT 0 NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `campus_stages` (
	`id` text PRIMARY KEY NOT NULL,
	`stage_number` integer NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`facility_id` text NOT NULL,
	`licensed_capacity` integer DEFAULT 16 NOT NULL,
	`operational_capacity` integer DEFAULT 16 NOT NULL,
	`current_census` integer DEFAULT 0 NOT NULL,
	`capacity_alert_threshold` integer DEFAULT 90 NOT NULL,
	`capacity_critical_threshold` integer DEFAULT 95 NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`activation_date` text,
	`deactivation_date` text,
	`awake_staff_ratio` text DEFAULT '1:8' NOT NULL,
	`overnight_staff_ratio` text DEFAULT '1:16' NOT NULL,
	`requires_lpha_assessment` integer DEFAULT false NOT NULL,
	`min_assessment_hours` integer DEFAULT 0 NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `case_management` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`case_manager_id` text,
	`case_manager_name` text,
	`function1_coordination` integer DEFAULT false NOT NULL,
	`function1_coordination_notes` text,
	`function2_referrals` integer DEFAULT false NOT NULL,
	`function2_referrals_json` text,
	`function3_collaterals` integer DEFAULT false NOT NULL,
	`function3_collaterals_json` text,
	`function4_barriers` integer DEFAULT false NOT NULL,
	`function4_barriers_json` text,
	`function5_monitoring` integer DEFAULT false NOT NULL,
	`function5_monitoring_notes` text,
	`function6_transition` integer DEFAULT false NOT NULL,
	`function6_transition_notes` text,
	`transition_plan_date` text,
	`projected_discharge_date` text,
	`status` text DEFAULT 'active' NOT NULL,
	`last_review_date` text,
	`next_review_date` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text,
	`updated_by` text
);
--> statement-breakpoint
CREATE TABLE `ccmg_care_coordination` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`ccmg_program_director_id` text,
	`ccmg_program_director_name` text,
	`case_manager_id` text,
	`case_manager_name` text,
	`assigned_department` text DEFAULT 'CCMG' NOT NULL,
	`department_transfer_date` text,
	`transferred_from` text,
	`transfer_rationale` text,
	`intake_completed` integer DEFAULT false NOT NULL,
	`intake_completed_date` text,
	`assessment_completed` integer DEFAULT false NOT NULL,
	`assessment_completed_date` text,
	`cans_completed` integer DEFAULT false NOT NULL,
	`cans_score` integer,
	`cans_risk_level` text,
	`gro_liaison_id` text,
	`gro_liaison_name` text,
	`gro_facility_id` text,
	`bed_assignment` text,
	`status` text DEFAULT 'intake' NOT NULL,
	`admission_date` text,
	`projected_discharge_date` text,
	`actual_discharge_date` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `ccmg_referrals` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`referral_type` text NOT NULL,
	`from_department` text NOT NULL,
	`to_department` text NOT NULL,
	`requested_by` text NOT NULL,
	`requested_by_id` text,
	`request_date` text,
	`reason_for_referral` text NOT NULL,
	`clinical_justification` text,
	`urgency` text DEFAULT 'routine' NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`accepted_by` text,
	`accepted_at` text,
	`scheduled_date` text,
	`completed_date` text,
	`outcome_notes` text,
	`follow_up_required` integer DEFAULT false NOT NULL,
	`follow_up_date` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `census_alerts` (
	`id` text PRIMARY KEY NOT NULL,
	`facility_id` text NOT NULL,
	`stage_id` text NOT NULL,
	`alert_type` text NOT NULL,
	`severity` text NOT NULL,
	`message` text NOT NULL,
	`current_census` integer NOT NULL,
	`capacity_limit` integer NOT NULL,
	`percent_full` integer NOT NULL,
	`triggered_at` text,
	`acknowledged_by` text,
	`acknowledged_at` text,
	`resolved_at` text,
	`auto_resolved` integer DEFAULT false NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `census_snapshots` (
	`id` text PRIMARY KEY NOT NULL,
	`facility_id` text NOT NULL,
	`snapshot_date` text NOT NULL,
	`snapshot_time` text DEFAULT '23:59:59' NOT NULL,
	`stage1_census` integer DEFAULT 0 NOT NULL,
	`stage2_census` integer DEFAULT 0 NOT NULL,
	`stage3_census` integer DEFAULT 0 NOT NULL,
	`total_census` integer DEFAULT 0 NOT NULL,
	`stage1_capacity` integer DEFAULT 16 NOT NULL,
	`stage2_capacity` integer DEFAULT 16 NOT NULL,
	`stage3_capacity` integer DEFAULT 16 NOT NULL,
	`total_capacity` integer DEFAULT 48 NOT NULL,
	`stage1_percent` integer DEFAULT 0 NOT NULL,
	`stage2_percent` integer DEFAULT 0 NOT NULL,
	`stage3_percent` integer DEFAULT 0 NOT NULL,
	`overall_percent` integer DEFAULT 0 NOT NULL,
	`alerts_triggered` integer DEFAULT 0 NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `chart_audits` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`audit_date` text NOT NULL,
	`auditor_name` text NOT NULL,
	`area1_identifying_info` integer DEFAULT false NOT NULL,
	`area1_notes` text,
	`area2_consent_forms` integer DEFAULT false NOT NULL,
	`area2_notes` text,
	`area3_assessment_current` integer DEFAULT false NOT NULL,
	`area3_notes` text,
	`area4_treatment_plan` integer DEFAULT false NOT NULL,
	`area4_notes` text,
	`area5_progress_notes` integer DEFAULT false NOT NULL,
	`area5_notes` text,
	`area6_medication_records` integer DEFAULT false NOT NULL,
	`area6_notes` text,
	`area7_safety_plans` integer DEFAULT false NOT NULL,
	`area7_notes` text,
	`area8_incident_reports` integer DEFAULT false NOT NULL,
	`area8_notes` text,
	`area9_authorization_billing` integer DEFAULT false NOT NULL,
	`area9_notes` text,
	`areas_passed` integer DEFAULT 0 NOT NULL,
	`areas_total` integer DEFAULT 9 NOT NULL,
	`overall_result` text DEFAULT 'incomplete',
	`corrective_actions` text,
	`follow_up_date` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `claim_line_items` (
	`id` text PRIMARY KEY NOT NULL,
	`claim_id` text NOT NULL,
	`service_date` text NOT NULL,
	`procedure_code` text NOT NULL,
	`diagnosis_code` text,
	`units` integer DEFAULT 1 NOT NULL,
	`unit_price` integer NOT NULL,
	`total_price` integer NOT NULL,
	`description` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `claims` (
	`id` text PRIMARY KEY NOT NULL,
	`claim_number` text NOT NULL,
	`patient_id` text NOT NULL,
	`payer_id` text,
	`clinician_id` text NOT NULL,
	`service_date` text NOT NULL,
	`submission_date` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`total_amount` integer NOT NULL,
	`allowed_amount` integer,
	`paid_amount` integer,
	`patient_responsibility` integer,
	`denial_reason` text,
	`denial_code` text,
	`appeal_date` text,
	`appeal_status` text DEFAULT 'not_appealed' NOT NULL,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `claims_claim_number_unique` ON `claims` (`claim_number`);--> statement-breakpoint
CREATE TABLE `clinical_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`patient_id` text NOT NULL,
	`treatment_plan_id` text,
	`clinician_id` text NOT NULL,
	`session_date` text NOT NULL,
	`session_type` text,
	`duration_minutes` integer DEFAULT 60 NOT NULL,
	`chief_complaint` text,
	`session_notes` text,
	`interventions_used_json` text DEFAULT '[]',
	`client_response` text,
	`plan_modifications` text,
	`risk_assessment_json` text,
	`next_session_date` text,
	`next_session_goals` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`billing_code` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `corrective_actions` (
	`id` text PRIMARY KEY NOT NULL,
	`action_number` text NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`related_audit_id` text,
	`related_incident_id` text,
	`priority` text NOT NULL,
	`status` text DEFAULT 'open' NOT NULL,
	`assigned_to` text NOT NULL,
	`due_date` text NOT NULL,
	`completed_at` text,
	`completion_notes` text,
	`verified_by` text,
	`verified_at` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `corrective_actions_action_number_unique` ON `corrective_actions` (`action_number`);--> statement-breakpoint
CREATE TABLE `credentials` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`credential_type` text NOT NULL,
	`license_number` text,
	`issuing_body` text,
	`issue_date` text,
	`expiry_date` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`document_id` text,
	`verified_by` text,
	`verified_at` text,
	`notes` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `crisis_debriefs` (
	`id` text PRIMARY KEY NOT NULL,
	`crisis_event_id` text NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`field1_event_summary` text,
	`field2_triggers_identified` text,
	`field3_early_warning_signs` text,
	`field4_interventions_used` text,
	`field5_what_worked` text,
	`field6_what_did_not_work` text,
	`field7_youth_perspective` text,
	`field8_staff_perspective` text,
	`field9_plan_adjustments` text,
	`safety_plan_updated` integer DEFAULT false NOT NULL,
	`safety_plan_changes` text,
	`follow_up_required` integer DEFAULT false NOT NULL,
	`follow_up_actions` text,
	`follow_up_date` text,
	`completed_by` text,
	`completed_by_id` text,
	`completed_at` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `crisis_events` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`crisis_type` text NOT NULL,
	`step1_identified` integer DEFAULT false NOT NULL,
	`step1_identified_at` text,
	`step1_identified_by` text,
	`step2_activated` integer DEFAULT false NOT NULL,
	`step2_activated_at` text,
	`step2_activated_by` text,
	`step3_responded` integer DEFAULT false NOT NULL,
	`step3_responded_at` text,
	`step3_responder_name` text,
	`step3_response_actions` text,
	`step4_ensured_safety` integer DEFAULT false NOT NULL,
	`step4_safety_measures` text,
	`step4_ensured_at` text,
	`step5_notified` integer DEFAULT false NOT NULL,
	`step5_notified_parties` text,
	`step5_notified_at` text,
	`step6_documented` integer DEFAULT false NOT NULL,
	`step6_documented_at` text,
	`step6_documentation_ref` text,
	`step7_reviewed` integer DEFAULT false NOT NULL,
	`step7_reviewed_at` text,
	`step7_reviewed_by` text,
	`step7_review_notes` text,
	`current_step` integer DEFAULT 1 NOT NULL,
	`overall_status` text DEFAULT 'active' NOT NULL,
	`youth_injured` integer DEFAULT false NOT NULL,
	`staff_injured` integer DEFAULT false NOT NULL,
	`restrictive_intervention_used` integer DEFAULT false NOT NULL,
	`restrictive_intervention_type` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `daily_observations` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`observation_date` text NOT NULL,
	`shift` text NOT NULL,
	`observed_by` text NOT NULL,
	`observed_by_id` text,
	`domain1_safety` integer DEFAULT false NOT NULL,
	`domain1_safety_notes` text,
	`domain1_safety_score` integer,
	`domain2_regulation` integer DEFAULT false NOT NULL,
	`domain2_regulation_notes` text,
	`domain2_regulation_score` integer,
	`domain3_functioning` integer DEFAULT false NOT NULL,
	`domain3_functioning_notes` text,
	`domain3_functioning_score` integer,
	`domain4_medication` integer DEFAULT false NOT NULL,
	`domain4_medication_notes` text,
	`domain4_medication_score` integer,
	`domain5_relationships` integer DEFAULT false NOT NULL,
	`domain5_relationships_notes` text,
	`domain5_relationships_score` integer,
	`domain6_participation` integer DEFAULT false NOT NULL,
	`domain6_participation_notes` text,
	`domain6_participation_score` integer,
	`clinically_significant` integer DEFAULT false NOT NULL,
	`clinical_concerns` text,
	`routed_to_clinician` integer DEFAULT false NOT NULL,
	`routed_to_clinician_id` text,
	`routed_to_clinician_name` text,
	`clinician_response` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `dms_documents` (
	`id` text PRIMARY KEY NOT NULL,
	`document_id` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`category_id` text NOT NULL,
	`category` text NOT NULL,
	`department` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`author_id` text NOT NULL,
	`author_name` text NOT NULL,
	`assigned_reviewer_id` text,
	`file_name` text,
	`file_type` text,
	`file_size` integer,
	`file_path` text,
	`tags_json` text DEFAULT '[]',
	`permissions_json` text DEFAULT '[]',
	`reviewed_at` text,
	`reviewed_by` text,
	`review_notes` text,
	`approved_at` text,
	`approved_by` text,
	`published_at` text,
	`published_by` text,
	`archived_at` text,
	`archived_by` text,
	`archive_reason` text,
	`superseded_by_id` text,
	`retention_years` integer DEFAULT 7,
	`expiry_date` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `dms_documents_document_id_unique` ON `dms_documents` (`document_id`);--> statement-breakpoint
CREATE TABLE `document_audit_log` (
	`id` text PRIMARY KEY NOT NULL,
	`document_id` text NOT NULL,
	`action` text NOT NULL,
	`actor_id` text NOT NULL,
	`actor_name` text NOT NULL,
	`from_status` text,
	`to_status` text,
	`details` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `document_categories` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`code` text NOT NULL,
	`description` text,
	`department` text,
	`parent_id` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `document_categories_code_unique` ON `document_categories` (`code`);--> statement-breakpoint
CREATE TABLE `document_templates` (
	`id` text PRIMARY KEY NOT NULL,
	`template_name` text NOT NULL,
	`template_code` text NOT NULL,
	`description` text,
	`document_type` text NOT NULL,
	`applicable_divisions` text DEFAULT 'all' NOT NULL,
	`cover_page_required` integer DEFAULT true NOT NULL,
	`toc_required` integer DEFAULT false NOT NULL,
	`signature_blocks` integer DEFAULT 0 NOT NULL,
	`primary_color` text DEFAULT '#245C5A' NOT NULL,
	`accent_color` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `document_templates_template_code_unique` ON `document_templates` (`template_code`);--> statement-breakpoint
CREATE TABLE `document_versions` (
	`id` text PRIMARY KEY NOT NULL,
	`document_id` text NOT NULL,
	`version_number` integer NOT NULL,
	`change_summary` text,
	`file_name` text,
	`file_path` text,
	`file_size` integer,
	`created_by` text NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`module_id` text NOT NULL,
	`record_name` text NOT NULL,
	`file_name` text NOT NULL,
	`file_type` text,
	`file_size` integer,
	`file_path` text,
	`uploaded_at` text,
	`uploaded_by` text,
	`verified_at` text,
	`verified_by` text,
	`status` text DEFAULT 'uploaded' NOT NULL,
	`expiry_date` text,
	`note` text
);
--> statement-breakpoint
CREATE TABLE `escalation_events` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`tier` text NOT NULL,
	`previous_tier` text,
	`trigger_source` text,
	`trigger_description` text NOT NULL,
	`trigger_detail` text,
	`response_actions` text,
	`responder_id` text,
	`responder_name` text,
	`responder_role` text,
	`responded_at` text,
	`resolution_notes` text,
	`resolved_at` text,
	`resolved_by` text,
	`status` text DEFAULT 'active' NOT NULL,
	`requires_post_crisis_review` integer DEFAULT false NOT NULL,
	`post_crisis_review_completed` integer DEFAULT false NOT NULL,
	`post_crisis_review_date` text,
	`post_crisis_review_by` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `facilities` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`code` text NOT NULL,
	`type` text NOT NULL,
	`address` text,
	`city` text,
	`state` text,
	`zip_code` text,
	`licensed_capacity` integer DEFAULT 0 NOT NULL,
	`operational_capacity` integer DEFAULT 0 NOT NULL,
	`current_occupancy` integer DEFAULT 0 NOT NULL,
	`total_rooms` integer DEFAULT 0 NOT NULL,
	`total_beds` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`activation_date` text,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `facility_phases` (
	`id` text PRIMARY KEY NOT NULL,
	`facility_id` text NOT NULL,
	`phase_name` text NOT NULL,
	`phase_number` integer NOT NULL,
	`beds_activated` integer DEFAULT 0 NOT NULL,
	`rooms_activated` integer DEFAULT 0 NOT NULL,
	`activation_date` text,
	`target_date` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`approved_by` text,
	`approval_date` text,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `family_contacts` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`contact_date` text NOT NULL,
	`contact_type` text NOT NULL,
	`contact_direction` text DEFAULT 'incoming' NOT NULL,
	`contacted_person` text NOT NULL,
	`relationship` text,
	`phone_number` text,
	`visit_start_time` text,
	`visit_end_time` text,
	`visit_location` text,
	`supervisor_present` text,
	`topics_discussed` text,
	`youth_participation` text,
	`concerns_raised` text,
	`action_items` text,
	`follow_up_needed` integer DEFAULT false NOT NULL,
	`follow_up_date` text,
	`outcome` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `form_instances` (
	`id` text PRIMARY KEY NOT NULL,
	`template_id` text NOT NULL,
	`person_id` text NOT NULL,
	`module_id` text,
	`packet_id` text,
	`status` text DEFAULT 'assigned' NOT NULL,
	`assigned_to_user_id` text,
	`assigned_by_user_id` text,
	`assigned_at` text,
	`due_date` text,
	`overdue_reminder_sent` integer DEFAULT false NOT NULL,
	`submitted_by_user_id` text,
	`submitted_at` text,
	`reviewed_by_user_id` text,
	`reviewed_at` text,
	`returned_reason` text,
	`approved_at` text,
	`locked_at` text,
	`dms_artifact_id` text,
	`field_values_json` text,
	`audit_version` integer DEFAULT 1 NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `form_packets` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`packet_type` text NOT NULL,
	`status` text DEFAULT 'packet-not-started' NOT NULL,
	`required_form_ids_json` text,
	`completed_form_ids_json` text,
	`missing_form_ids_json` text,
	`packet_artifact_id` text,
	`created_at` text,
	`approved_at` text,
	`filed_at` text
);
--> statement-breakpoint
CREATE TABLE `form_role_bindings` (
	`id` text PRIMARY KEY NOT NULL,
	`template_id` text NOT NULL,
	`role` text NOT NULL,
	`is_required` integer DEFAULT false NOT NULL,
	`is_auto_assigned` integer DEFAULT true NOT NULL,
	`assignment_trigger` text DEFAULT 'on-create' NOT NULL,
	`due_days` integer DEFAULT 7 NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `form_template_fields` (
	`id` text PRIMARY KEY NOT NULL,
	`template_id` text NOT NULL,
	`name` text NOT NULL,
	`label` text NOT NULL,
	`field_type` text NOT NULL,
	`required` integer DEFAULT false NOT NULL,
	`options_json` text,
	`placeholder` text,
	`help_text` text,
	`default_value` text,
	`validation_regex` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`section` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `form_templates` (
	`id` text PRIMARY KEY NOT NULL,
	`form_code` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`binder_area` text NOT NULL,
	`binder_area_index` integer DEFAULT 0 NOT NULL,
	`lifecycle_module` text,
	`role_applicability_json` text,
	`triggering_status` text,
	`required_for_gate` integer DEFAULT false NOT NULL,
	`signature_required` integer DEFAULT false NOT NULL,
	`reviewer_required` integer DEFAULT false NOT NULL,
	`output_format` text DEFAULT 'pdf' NOT NULL,
	`source_pdf_path` text,
	`active_version` integer DEFAULT 1 NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`retention_category` text,
	`renewal_rule` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `form_templates_form_code_unique` ON `form_templates` (`form_code`);--> statement-breakpoint
CREATE TABLE `generated_documents` (
	`id` text PRIMARY KEY NOT NULL,
	`template_id` text NOT NULL,
	`template_code` text NOT NULL,
	`document_title` text NOT NULL,
	`youth_id` text,
	`youth_name` text,
	`mrn` text,
	`generated_by` text NOT NULL,
	`generated_by_id` text,
	`division` text,
	`status` text DEFAULT 'queued' NOT NULL,
	`file_path` text,
	`file_size` integer,
	`page_count` integer,
	`error_message` text,
	`created_at` text,
	`completed_at` text
);
--> statement-breakpoint
CREATE TABLE `hr_people` (
	`id` text PRIMARY KEY NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`employee_id` text,
	`role` text NOT NULL,
	`department` text NOT NULL,
	`lane` text DEFAULT 'activation' NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`is_employee` integer DEFAULT false NOT NULL,
	`hire_date` text,
	`supervisor` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `incidents` (
	`id` text PRIMARY KEY NOT NULL,
	`incident_number` text NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`incident_type` text NOT NULL,
	`severity` text NOT NULL,
	`status` text DEFAULT 'open' NOT NULL,
	`patient_id` text,
	`reported_by` text NOT NULL,
	`assigned_to` text,
	`occurred_at` text NOT NULL,
	`resolved_at` text,
	`resolution_notes` text,
	`follow_up_required` integer DEFAULT false NOT NULL,
	`follow_up_date` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `incidents_incident_number_unique` ON `incidents` (`incident_number`);--> statement-breakpoint
CREATE TABLE `insurance_plans` (
	`id` text PRIMARY KEY NOT NULL,
	`payer_name` text NOT NULL,
	`plan_name` text NOT NULL,
	`policy_number_pattern` text,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `intake_pipeline` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`mrn` text NOT NULL,
	`youth_name` text NOT NULL,
	`referral_received_date` text,
	`referral_received_by` text,
	`referral_received_notes` text,
	`referral_received_completed` integer DEFAULT false NOT NULL,
	`screening_date` text,
	`screening_completed_by` text,
	`screening_result` text,
	`screening_notes` text,
	`screening_completed` integer DEFAULT false NOT NULL,
	`consent_date` text,
	`consent_completed_by` text,
	`guardian_consent_obtained` integer DEFAULT false NOT NULL,
	`youth_assent_obtained` integer DEFAULT false NOT NULL,
	`hipaa_acknowledgment` integer DEFAULT false NOT NULL,
	`rights_acknowledgment` integer DEFAULT false NOT NULL,
	`consent_notes` text,
	`consent_completed` integer DEFAULT false NOT NULL,
	`payer_verification_date` text,
	`payer_verification_completed_by` text,
	`benefits_verified` integer DEFAULT false NOT NULL,
	`authorization_required` integer DEFAULT false NOT NULL,
	`authorization_submitted` integer DEFAULT false NOT NULL,
	`authorization_approved` integer DEFAULT false NOT NULL,
	`payer_notes` text,
	`payer_completed` integer DEFAULT false NOT NULL,
	`disposition_date` text,
	`disposition_completed_by` text,
	`disposition` text,
	`disposition_reason` text,
	`bed_assigned` text,
	`admission_scheduled_date` text,
	`disposition_completed` integer DEFAULT false NOT NULL,
	`current_step` text DEFAULT 'referral' NOT NULL,
	`overall_status` text DEFAULT 'in_progress' NOT NULL,
	`is_blocked` integer DEFAULT false NOT NULL,
	`block_reason` text,
	`referral_elapsed_hours` integer DEFAULT 0,
	`screening_elapsed_hours` integer DEFAULT 0,
	`consent_elapsed_hours` integer DEFAULT 0,
	`payer_elapsed_hours` integer DEFAULT 0,
	`disposition_elapsed_hours` integer DEFAULT 0,
	`created_at` text,
	`updated_at` text,
	`created_by` text,
	`updated_by` text
);
--> statement-breakpoint
CREATE TABLE `medication_administrations` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`medication_name` text NOT NULL,
	`generic_name` text,
	`dosage` text NOT NULL,
	`route` text NOT NULL,
	`frequency` text NOT NULL,
	`indication` text,
	`prescribing_provider` text,
	`prescription_date` text,
	`scheduled_time` text NOT NULL,
	`admin_date` text NOT NULL,
	`admin_time` text,
	`administered_by` text,
	`witnessed_by` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`refusal_reason` text,
	`hold_reason` text,
	`is_prn` integer DEFAULT false NOT NULL,
	`prn_reason` text,
	`prn_effectiveness` text,
	`is_controlled` integer DEFAULT false NOT NULL,
	`controlled_count_before` integer,
	`controlled_count_after` integer,
	`waste_witnessed_by` text,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `meeting_action_items` (
	`id` text PRIMARY KEY NOT NULL,
	`meeting_id` text NOT NULL,
	`description` text NOT NULL,
	`assigned_to_id` text,
	`assigned_to_name` text,
	`priority` text DEFAULT 'medium' NOT NULL,
	`due_date` text,
	`status` text DEFAULT 'open' NOT NULL,
	`completed_at` text,
	`completed_by` text,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `meetings` (
	`id` text PRIMARY KEY NOT NULL,
	`meeting_type` text NOT NULL,
	`title` text NOT NULL,
	`scheduled_date` text NOT NULL,
	`scheduled_time` text,
	`duration_minutes` integer DEFAULT 30,
	`facilitator_id` text,
	`facilitator_name` text,
	`attendees_json` text,
	`youth_ids_json` text,
	`agenda_json` text,
	`notes` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`completed_at` text,
	`follow_up_required` integer DEFAULT false NOT NULL,
	`follow_up_notes` text,
	`next_meeting_date` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `mgma_domains` (
	`id` text PRIMARY KEY NOT NULL,
	`domain_number` integer NOT NULL,
	`domain_name` text NOT NULL,
	`domain_description` text NOT NULL,
	`amos_ops_module` text NOT NULL,
	`module_route` text NOT NULL,
	`responsible_division` text NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`configured_at` text,
	`configured_by` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `mgma_kpi_targets` (
	`id` text PRIMARY KEY NOT NULL,
	`domain_id` text NOT NULL,
	`kpi_name` text NOT NULL,
	`kpi_description` text NOT NULL,
	`target_value` text NOT NULL,
	`target_unit` text NOT NULL,
	`comparison_operator` text DEFAULT 'less_than' NOT NULL,
	`benchmark_source` text DEFAULT 'MGMA 2024' NOT NULL,
	`current_value` text,
	`last_measured_at` text,
	`measurement_frequency` text DEFAULT 'monthly' NOT NULL,
	`status` text DEFAULT 'not_measured' NOT NULL,
	`alert_threshold` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `mgma_scorecards` (
	`id` text PRIMARY KEY NOT NULL,
	`division` text NOT NULL,
	`scorecard_date` text NOT NULL,
	`overall_score` integer,
	`kpis_on_target` integer DEFAULT 0 NOT NULL,
	`kpis_at_risk` integer DEFAULT 0 NOT NULL,
	`kpis_off_target` integer DEFAULT 0 NOT NULL,
	`kpis_not_measured` integer DEFAULT 0 NOT NULL,
	`domain_scores_json` text,
	`executive_summary` text,
	`action_items` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `mhrs_encounters` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`service_plan_id` text NOT NULL,
	`therapist_id` text NOT NULL,
	`therapist_name` text NOT NULL,
	`encounter_date` text NOT NULL,
	`encounter_type` text NOT NULL,
	`billing_code` text DEFAULT 'H2017' NOT NULL,
	`units_billed` integer DEFAULT 1 NOT NULL,
	`minutes_delivered` integer DEFAULT 15 NOT NULL,
	`mhrs_category` text NOT NULL,
	`cans_domain_targeted` text,
	`service_description` text NOT NULL,
	`skills_taught` text,
	`youth_progress` text,
	`barriers_identified` text,
	`homework_assignment` text,
	`next_steps` text,
	`goal_progress` text DEFAULT 'no_change',
	`cans_score_current` integer,
	`documentation_status` text DEFAULT 'draft' NOT NULL,
	`signed_by` text,
	`signed_at` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `mhrs_service_plans` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`mhrs_supervisor_id` text,
	`mhrs_supervisor_name` text,
	`therapist_id` text,
	`therapist_name` text,
	`plan_status` text DEFAULT 'draft' NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`intake_date` text NOT NULL,
	`plan_due_date` text NOT NULL,
	`plan_completed_date` text,
	`next_review_due` text,
	`last_review_date` text,
	`cat1_psycho_goal` text,
	`cat1_psycho_objectives` text,
	`cat1_psycho_completed` integer DEFAULT false NOT NULL,
	`cat2_skills_goal` text,
	`cat2_skills_objectives` text,
	`cat2_skills_completed` integer DEFAULT false NOT NULL,
	`cat3_supportive_goal` text,
	`cat3_supportive_objectives` text,
	`cat3_supportive_completed` integer DEFAULT false NOT NULL,
	`cat4_community_goal` text,
	`cat4_community_objectives` text,
	`cat4_community_completed` integer DEFAULT false NOT NULL,
	`cans_domain_primary` text,
	`cans_domain_secondary` text,
	`cans_baseline_score` integer,
	`cans_target_score` integer,
	`prepared_by` text,
	`prepared_at` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`approved_by` text,
	`approved_at` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `mhrs_skills_assessments` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`service_plan_id` text NOT NULL,
	`assessed_by` text NOT NULL,
	`assessed_by_id` text,
	`assessment_date` text NOT NULL,
	`cans_domain` text NOT NULL,
	`skill_areas_json` text NOT NULL,
	`overall_baseline` integer,
	`overall_current` integer,
	`overall_target` integer,
	`progress_percentage` integer,
	`readiness_for_transition` text DEFAULT 'not_ready',
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `mhtcm_eligibility` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`age_qualified` integer DEFAULT false NOT NULL,
	`diagnosis_qualified` integer DEFAULT false NOT NULL,
	`functional_impairment` integer DEFAULT false NOT NULL,
	`medicaid_eligible` integer DEFAULT false NOT NULL,
	`primary_diagnosis` text,
	`primary_diagnosis_code` text,
	`secondary_diagnosis` text,
	`secondary_diagnosis_code` text,
	`eligibility_status` text DEFAULT 'pending' NOT NULL,
	`determined_by` text,
	`determined_at` text,
	`determination_rationale` text,
	`cans_assessment_id` text,
	`cans_total_score` integer,
	`effective_date` text,
	`expiration_date` text,
	`reauthorization_due` text,
	`reauthorization_status` text DEFAULT 'not_due',
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `mhtcm_encounters` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`service_plan_id` text NOT NULL,
	`case_manager_id` text NOT NULL,
	`case_manager_name` text NOT NULL,
	`encounter_date` text NOT NULL,
	`encounter_type` text NOT NULL,
	`billing_code` text DEFAULT 'T1017' NOT NULL,
	`units_billed` integer DEFAULT 1 NOT NULL,
	`minutes_delivered` integer DEFAULT 15 NOT NULL,
	`mhtcm_function` text NOT NULL,
	`service_description` text NOT NULL,
	`barriers_identified` text,
	`interventions_provided` text,
	`youth_response` text,
	`plan_modifications` text,
	`next_steps` text,
	`collateral_contacts_json` text,
	`goal_progress` text DEFAULT 'no_change',
	`follow_up_required` integer DEFAULT false NOT NULL,
	`follow_up_date` text,
	`follow_up_actions` text,
	`documentation_status` text DEFAULT 'draft' NOT NULL,
	`signed_by` text,
	`signed_at` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `mhtcm_service_plans` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`case_manager_id` text NOT NULL,
	`case_manager_name` text NOT NULL,
	`plan_status` text DEFAULT 'draft' NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`intake_date` text NOT NULL,
	`plan_due_date` text NOT NULL,
	`plan_completed_date` text,
	`next_review_due` text,
	`last_review_date` text,
	`function1_intake_goal` text,
	`function1_intake_completed` integer DEFAULT false NOT NULL,
	`function2_eligibility_goal` text,
	`function2_eligibility_completed` integer DEFAULT false NOT NULL,
	`function3_coordination_goal` text,
	`function3_coordination_completed` integer DEFAULT false NOT NULL,
	`function4_referral_goal` text,
	`function4_referral_completed` integer DEFAULT false NOT NULL,
	`function5_monitoring_goal` text,
	`function5_monitoring_completed` integer DEFAULT false NOT NULL,
	`function6_transition_goal` text,
	`function6_transition_completed` integer DEFAULT false NOT NULL,
	`cans_score_at_intake` integer,
	`cans_risk_level` text,
	`loc_determined` integer DEFAULT false NOT NULL,
	`loc_level` text DEFAULT 'not_determined',
	`prepared_by` text,
	`prepared_at` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`approved_by` text,
	`approved_at` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `milieu_notes` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`note_date` text NOT NULL,
	`shift` text NOT NULL,
	`recorded_by` text NOT NULL,
	`wake_time` text,
	`bedtime` text,
	`meals_eaten` text,
	`hygiene_status` text,
	`activities_participated` text,
	`activity_notes` text,
	`school_attendance` text,
	`school_notes` text,
	`mood` text,
	`affect` text,
	`social_interactions` text,
	`sleep_quality` text,
	`staff_notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `module_statuses` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`module_id` text NOT NULL,
	`status_id` text NOT NULL,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `ms_graph_groups` (
	`id` text PRIMARY KEY NOT NULL,
	`entra_id` text NOT NULL,
	`display_name` text NOT NULL,
	`description` text,
	`group_type` text,
	`security_enabled` integer,
	`mail_enabled` integer,
	`member_count` integer DEFAULT 0,
	`last_sync_at` text,
	`created_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ms_graph_groups_entra_id_unique` ON `ms_graph_groups` (`entra_id`);--> statement-breakpoint
CREATE TABLE `ms_graph_sync_log` (
	`id` text PRIMARY KEY NOT NULL,
	`sync_type` text NOT NULL,
	`status` text NOT NULL,
	`users_synced` integer DEFAULT 0,
	`groups_synced` integer DEFAULT 0,
	`errors_json` text,
	`started_at` text,
	`completed_at` text
);
--> statement-breakpoint
CREATE TABLE `ms_graph_users` (
	`id` text PRIMARY KEY NOT NULL,
	`entra_id` text NOT NULL,
	`display_name` text NOT NULL,
	`given_name` text,
	`surname` text,
	`user_principal_name` text NOT NULL,
	`mail` text,
	`job_title` text,
	`department` text,
	`office_location` text,
	`account_enabled` integer DEFAULT true NOT NULL,
	`sync_status` text DEFAULT 'pending' NOT NULL,
	`last_sync_at` text,
	`created_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ms_graph_users_entra_id_unique` ON `ms_graph_users` (`entra_id`);--> statement-breakpoint
CREATE TABLE `nil_entities` (
	`id` text PRIMARY KEY NOT NULL,
	`entity_type` text NOT NULL,
	`source_id` text,
	`source_table` text,
	`display_name` text NOT NULL,
	`description` text,
	`metadata` text,
	`module` text DEFAULT 'unknown' NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `nil_relationships` (
	`id` text PRIMARY KEY NOT NULL,
	`from_entity_id` text NOT NULL,
	`to_entity_id` text NOT NULL,
	`relation_type` text NOT NULL,
	`strength` integer DEFAULT 1 NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`message` text NOT NULL,
	`person_name` text,
	`module_name` text,
	`action_href` text,
	`is_read` integer DEFAULT false NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `outcome_measures` (
	`id` text PRIMARY KEY NOT NULL,
	`patient_id` text NOT NULL,
	`session_id` text,
	`measure_type` text NOT NULL,
	`score` integer NOT NULL,
	`max_score` integer NOT NULL,
	`severity_level` text,
	`administered_by` text NOT NULL,
	`administered_at` text,
	`notes` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `part2_audit_log` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`mrn` text NOT NULL,
	`sud_record_id` text NOT NULL,
	`access_type` text NOT NULL,
	`accessed_by` text NOT NULL,
	`accessed_by_id` text,
	`accessed_by_role` text,
	`access_timestamp` text,
	`access_context` text NOT NULL,
	`consent_id` text,
	`qsoa_id` text,
	`record_type_accessed` text NOT NULL,
	`fields_accessed` text,
	`unauthorized_flag` integer DEFAULT false NOT NULL,
	`flag_reason` text,
	`ip_address` text,
	`session_id` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `part2_breach_notifications` (
	`id` text PRIMARY KEY NOT NULL,
	`breach_number` text NOT NULL,
	`discovered_date` text NOT NULL,
	`breach_type` text NOT NULL,
	`description` text NOT NULL,
	`affected_youth_count` integer DEFAULT 0 NOT NULL,
	`affected_record_count` integer DEFAULT 0 NOT NULL,
	`affected_youth_json` text,
	`containment_actions` text,
	`mitigation_actions` text,
	`secretary_notified` integer DEFAULT false NOT NULL,
	`secretary_notified_at` text,
	`patients_notified` integer DEFAULT false NOT NULL,
	`patients_notified_at` text,
	`patients_notified_by` text,
	`status` text DEFAULT 'open' NOT NULL,
	`closed_at` text,
	`closed_by` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `part2_breach_notifications_breach_number_unique` ON `part2_breach_notifications` (`breach_number`);--> statement-breakpoint
CREATE TABLE `part2_consents` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`sud_record_id` text NOT NULL,
	`consent_type` text NOT NULL,
	`recipient_name` text NOT NULL,
	`recipient_organization` text,
	`recipient_type` text NOT NULL,
	`recipient_npi` text,
	`information_scope` text DEFAULT 'full_record' NOT NULL,
	`specific_elements` text,
	`purpose` text NOT NULL,
	`effective_date` text NOT NULL,
	`expiration_date` text,
	`expiration_event` text DEFAULT 'fixed_date',
	`authorized_by` text NOT NULL,
	`guardian_name` text,
	`guardian_relationship` text,
	`youth_signature` text,
	`guardian_signature` text,
	`witness_name` text,
	`witness_signature` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`revoked_at` text,
	`revoked_by` text,
	`revocation_reason` text,
	`is_qsoa` integer DEFAULT false NOT NULL,
	`qsoa_agreement_id` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `patients` (
	`id` text PRIMARY KEY NOT NULL,
	`mrn` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`date_of_birth` text NOT NULL,
	`gender` text,
	`phone` text,
	`email` text,
	`address` text,
	`insurance_id` text,
	`emergency_name` text,
	`emergency_phone` text,
	`referral_source` text,
	`status` text DEFAULT 'intake' NOT NULL,
	`assigned_clinician_id` text,
	`intake_date` text,
	`discharge_date` text,
	`discharge_reason` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text,
	`updated_by` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `patients_mrn_unique` ON `patients` (`mrn`);--> statement-breakpoint
CREATE TABLE `payers` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`payer_type` text DEFAULT 'insurance' NOT NULL,
	`contact_phone` text,
	`contact_email` text,
	`claims_address` text,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `performance_reviews` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`review_type` text NOT NULL,
	`review_date` text NOT NULL,
	`competencies` text,
	`goals` text,
	`supervisor_comments` text,
	`action_items` text,
	`overall_rating` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`signed_off_by` text,
	`signed_off_at` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `prohibited_practices` (
	`id` text PRIMARY KEY NOT NULL,
	`incident_id` text NOT NULL,
	`incident_number` text NOT NULL,
	`youth_id` text NOT NULL,
	`prone_restraint_used` integer DEFAULT false NOT NULL,
	`supine_restraint_used` integer DEFAULT false NOT NULL,
	`mechanical_restraint_used` integer DEFAULT false NOT NULL,
	`chemical_restraint_used` integer DEFAULT false NOT NULL,
	`denial_of_meals` integer DEFAULT false NOT NULL,
	`denial_of_sleep` integer DEFAULT false NOT NULL,
	`corporal_punishment` integer DEFAULT false NOT NULL,
	`humiliation_degradation` integer DEFAULT false NOT NULL,
	`certified` integer DEFAULT false NOT NULL,
	`certified_by` text,
	`certified_at` text,
	`notes` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `qsoa_agreements` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_name` text NOT NULL,
	`organization_type` text NOT NULL,
	`contact_name` text,
	`contact_phone` text,
	`contact_email` text,
	`agreement_date` text NOT NULL,
	`effective_date` text NOT NULL,
	`expiration_date` text,
	`auto_renew` integer DEFAULT false NOT NULL,
	`services_provided` text NOT NULL,
	`data_access_scope` text DEFAULT 'limited' NOT NULL,
	`data_access_description` text,
	`baa_executed` integer DEFAULT false NOT NULL,
	`baa_date` text,
	`staff_trained` integer DEFAULT false NOT NULL,
	`training_date` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `record_retention` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`record_type` text NOT NULL,
	`created_date` text NOT NULL,
	`retention_years` integer DEFAULT 5 NOT NULL,
	`expiration_date` text NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`destroyed_by` text,
	`destroyed_at` text,
	`destruction_authorization` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `referral_checklists` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`intake_id` text NOT NULL,
	`item1_referral_form_received` integer DEFAULT false NOT NULL,
	`item2_demographics_complete` integer DEFAULT false NOT NULL,
	`item3_insurance_verified` integer DEFAULT false NOT NULL,
	`item4_consent_for_release` integer DEFAULT false NOT NULL,
	`item5_psychiatric_history` integer DEFAULT false NOT NULL,
	`item6_medical_records_requested` integer DEFAULT false NOT NULL,
	`item7_educational_records_requested` integer DEFAULT false NOT NULL,
	`item8_legal_status_confirmed` integer DEFAULT false NOT NULL,
	`item9_guardian_contact_verified` integer DEFAULT false NOT NULL,
	`item10_service_activation_date_set` integer DEFAULT false NOT NULL,
	`items_completed` integer DEFAULT 0 NOT NULL,
	`items_total` integer DEFAULT 10 NOT NULL,
	`all_items_complete` integer DEFAULT false NOT NULL,
	`completed_by` text,
	`completed_at` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `restraint_incidents` (
	`id` text PRIMARY KEY NOT NULL,
	`incident_number` text NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`incident_date` text NOT NULL,
	`incident_time` text NOT NULL,
	`incident_location` text NOT NULL,
	`incident_type` text NOT NULL,
	`primary_staff_id` text NOT NULL,
	`primary_staff_name` text NOT NULL,
	`secondary_staff_id` text,
	`secondary_staff_name` text,
	`supervisor_notified_at` text,
	`precipitating_factors` text NOT NULL,
	`youth_behavior` text NOT NULL,
	`deescalation_attempts` text NOT NULL,
	`less_restrictive_alternatives` text,
	`intervention_started_at` text NOT NULL,
	`intervention_ended_at` text,
	`duration_minutes` integer,
	`youth_injuries` text,
	`staff_injuries` text,
	`medical_attention_required` integer DEFAULT false NOT NULL,
	`medical_evaluation_completed` integer DEFAULT false NOT NULL,
	`medical_evaluation_completed_at` text,
	`medical_evaluation_by` text,
	`initial_documentation_completed` integer DEFAULT false NOT NULL,
	`initial_documentation_due` text,
	`initial_documentation_completed_at` text,
	`follow_up_review_completed` integer DEFAULT false NOT NULL,
	`follow_up_review_due` text,
	`follow_up_review_completed_at` text,
	`follow_up_actions` text,
	`status` text DEFAULT 'open' NOT NULL,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `restraint_incidents_incident_number_unique` ON `restraint_incidents` (`incident_number`);--> statement-breakpoint
CREATE TABLE `restrictive_interventions` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`intervention_type` text NOT NULL,
	`incident_date` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text,
	`duration_minutes` integer,
	`initiated_by` text NOT NULL,
	`initiated_by_role` text,
	`witnesses` text,
	`precipitating_factors` text,
	`alternatives_attempted` text,
	`youth_injuries` text,
	`staff_injuries` text,
	`medical_assessment` text,
	`debrief_completed` integer DEFAULT false NOT NULL,
	`debrief_date` text,
	`debrief_notes` text,
	`guardian_notified` integer DEFAULT false NOT NULL,
	`guardian_notification_date` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `rooms` (
	`id` text PRIMARY KEY NOT NULL,
	`facility_id` text NOT NULL,
	`room_number` text NOT NULL,
	`floor` text DEFAULT 'ground' NOT NULL,
	`room_type` text DEFAULT 'standard' NOT NULL,
	`max_beds` integer DEFAULT 2 NOT NULL,
	`current_occupancy` integer DEFAULT 0 NOT NULL,
	`bed_layout` text DEFAULT 'double' NOT NULL,
	`has_private_bath` integer DEFAULT false NOT NULL,
	`has_window` integer DEFAULT true NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`phase_activation_id` text,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `separation_checklists` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`item_id` text NOT NULL,
	`label` text NOT NULL,
	`category` text NOT NULL,
	`completed` integer DEFAULT false NOT NULL,
	`completed_by` text,
	`completed_at` text,
	`notes` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `shift_handoffs` (
	`id` text PRIMARY KEY NOT NULL,
	`from_shift_id` text NOT NULL,
	`to_shift_id` text,
	`handoff_date` text NOT NULL,
	`from_staff_name` text NOT NULL,
	`to_staff_name` text,
	`youth_status_json` text,
	`pending_items` text,
	`medication_updates` text,
	`appointment_reminders` text,
	`high_priority_alerts` text,
	`safety_alerts` text,
	`general_notes` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`completed_at` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `shifts` (
	`id` text PRIMARY KEY NOT NULL,
	`shift_date` text NOT NULL,
	`shift_type` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`rcs_lead_id` text,
	`rcs_lead_name` text,
	`rcs_staff_ids_json` text,
	`nurse_id` text,
	`nurse_name` text,
	`clinician_on_call` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`coverage_status` text DEFAULT 'full' NOT NULL,
	`coverage_notes` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `stage_assignments` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`from_stage_id` text,
	`to_stage_id` text NOT NULL,
	`assignment_type` text DEFAULT 'initial' NOT NULL,
	`assigned_by` text NOT NULL,
	`assigned_by_id` text,
	`assignment_rationale` text,
	`projected_duration_days` integer,
	`bed_assignment` text,
	`completed_date` text,
	`completion_outcome` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `stage_progression_criteria` (
	`id` text PRIMARY KEY NOT NULL,
	`stage_id` text NOT NULL,
	`criterion_number` integer NOT NULL,
	`criterion_name` text NOT NULL,
	`description` text NOT NULL,
	`required_for_progression` integer DEFAULT true NOT NULL,
	`assessment_tool` text,
	`target_score` text,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `status_transitions` (
	`id` text PRIMARY KEY NOT NULL,
	`person_id` text NOT NULL,
	`person_name` text NOT NULL,
	`module_id` text NOT NULL,
	`module_name` text NOT NULL,
	`from_status` text NOT NULL,
	`to_status` text NOT NULL,
	`changed_by` text NOT NULL,
	`changed_at` text,
	`note` text
);
--> statement-breakpoint
CREATE TABLE `sud_records` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`substance_type` text NOT NULL,
	`diagnosis_code` text,
	`severity` text,
	`is_part2_protected` integer DEFAULT true NOT NULL,
	`part2_designation_date` text,
	`status` text DEFAULT 'active' NOT NULL,
	`assessment_date` text NOT NULL,
	`assessing_clinician_id` text,
	`assessing_clinician_name` text,
	`treatment_plan_reference` text,
	`notes` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text
);
--> statement-breakpoint
CREATE TABLE `training_modules` (
	`id` text PRIMARY KEY NOT NULL,
	`track_id` text NOT NULL,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`description` text,
	`step_count` integer DEFAULT 5 NOT NULL,
	`created_at` text
);
--> statement-breakpoint
CREATE TABLE `training_progress` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`module_id` text NOT NULL,
	`completed_steps` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'available' NOT NULL,
	`quiz_score` integer,
	`quiz_passed` integer DEFAULT false,
	`started_at` text,
	`completed_at` text
);
--> statement-breakpoint
CREATE TABLE `treatment_plans` (
	`id` text PRIMARY KEY NOT NULL,
	`patient_id` text NOT NULL,
	`plan_number` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`primary_diagnosis` text NOT NULL,
	`secondary_diagnosis` text,
	`presenting_problem` text NOT NULL,
	`goals_json` text DEFAULT '[]' NOT NULL,
	`interventions_json` text DEFAULT '[]' NOT NULL,
	`estimated_duration_weeks` integer,
	`start_date` text,
	`review_date` text,
	`end_date` text,
	`assigned_clinician_id` text NOT NULL,
	`supervisor_id` text,
	`approved_by` text,
	`approved_at` text,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`password_hash` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`role` text DEFAULT 'rcs-day' NOT NULL,
	`department` text,
	`is_active` integer DEFAULT true NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);--> statement-breakpoint
CREATE TABLE `youth_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`mrn` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`date_of_birth` text NOT NULL,
	`age` integer NOT NULL,
	`gender` text,
	`race` text,
	`ethnicity` text,
	`preferred_language` text DEFAULT 'English',
	`phone` text,
	`email` text,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`guardian1_name` text NOT NULL,
	`guardian1_relationship` text NOT NULL,
	`guardian1_phone` text NOT NULL,
	`guardian1_email` text,
	`guardian2_name` text,
	`guardian2_relationship` text,
	`guardian2_phone` text,
	`guardian2_email` text,
	`emergency_name` text,
	`emergency_relationship` text,
	`emergency_phone` text,
	`referral_source_type` text,
	`referral_source_name` text,
	`referral_source_phone` text,
	`referred_by` text,
	`referral_date` text,
	`assigned_clinician_id` text,
	`assigned_clinician_name` text,
	`assigned_case_manager_id` text,
	`assigned_case_manager_name` text,
	`status` text DEFAULT 'referral_pending' NOT NULL,
	`level_of_care` text DEFAULT 'not_yet_determined',
	`bed_assignment` text,
	`primary_payer_id` text,
	`primary_payer_name` text,
	`policy_number` text,
	`group_number` text,
	`subscriber_name` text,
	`subscriber_relationship` text,
	`admission_date` text,
	`projected_discharge_date` text,
	`actual_discharge_date` text,
	`discharge_reason` text,
	`discharge_disposition` text,
	`created_at` text,
	`updated_at` text,
	`created_by` text,
	`updated_by` text,
	`notes` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `youth_profiles_mrn_unique` ON `youth_profiles` (`mrn`);--> statement-breakpoint
CREATE TABLE `youth_rights_acknowledgments` (
	`id` text PRIMARY KEY NOT NULL,
	`youth_id` text NOT NULL,
	`youth_name` text NOT NULL,
	`mrn` text NOT NULL,
	`rights_version` text DEFAULT '2024-01' NOT NULL,
	`rights_document_url` text,
	`acknowledged_by_youth` integer DEFAULT false NOT NULL,
	`youth_acknowledged_at` text,
	`acknowledged_by_guardian` integer DEFAULT false NOT NULL,
	`guardian_acknowledged_at` text,
	`guardian_name` text,
	`delivered_by` text NOT NULL,
	`delivered_by_id` text,
	`delivered_at` text,
	`delivery_method` text DEFAULT 'in_person' NOT NULL,
	`language` text DEFAULT 'English' NOT NULL,
	`interpreter_used` integer DEFAULT false NOT NULL,
	`interpreter_name` text,
	`notes` text,
	`created_at` text,
	`updated_at` text
);
