import { z } from "zod";

const shortText = z.string().max(240);
const detailText = z.string().max(2_000);
const nullableDetail = detailText.nullable();

export const clinicalBillingEvaluationSchema = z.object({
  evaluatedOn: shortText,
  acknowledgedPolicyVersion: shortText,
  encounter: z.object({
    encounterId: shortText,
    clientId: shortText,
    program: z.enum(["MHTCM", "MHRS"]),
    procedureCode: shortText,
    modifiers: z.array(shortText).max(12),
    serviceDate: shortText,
    startTime: shortText,
    endTime: shortText,
    declaredUnits: z.number().finite(),
    ageYears: z.number().finite(),
    deliveryMode: z.enum(["in_person", "synchronous_audiovisual", "synchronous_audio_only"]),
    setting: z.enum(["individual", "group"]),
    groupSize: z.number().finite().optional(),
    fundingSource: z.enum(["standard", "criminal_justice_agency"]),
    continuousContact: z.boolean(),
    personPresentAwakeParticipating: z.boolean(),
    collateralContact: z.boolean(),
    personOrLarPresentForCollateral: z.boolean(),
    mhtcmFunction: z.enum([
      "intake_screening",
      "eligibility",
      "care_coordination",
      "referral_management",
      "discharge_planning",
      "aftercare_follow_up",
    ]).optional(),
    mhtcmLevel: z.enum(["routine", "intensive"]).optional(),
    mhrsCategory: z.enum([
      "psychosocial_rehabilitation",
      "skills_training",
      "supportive_interventions",
      "community_integration",
    ]).optional(),
    mhrsServiceBasis: z.enum([
      "psychosocial_rehabilitation",
      "skills_training_and_development",
    ]).optional(),
    emergentTreatment: z.boolean(),
    duplicatesAnotherServiceOrDischargeActivity: z.boolean(),
  }),
  eligibility: z.object({
    medicaidEligible: z.boolean(),
    texasResident: z.boolean(),
    diagnosisCategory: z.enum([
      "mental_illness",
      "serious_emotional_disturbance",
      "serious_mental_illness",
      "idd_only",
      "substance_use_disorder_only",
    ]),
    diagnosisEstablishedOn: shortText.nullable(),
    diagnosisLastReviewedOn: shortText.nullable(),
    diagnosticCriteriaDocumented: z.boolean(),
    functionalEligibilityConfirmed: z.boolean(),
    uniformAssessment: z.enum(["CANS", "ANSA"]).nullable(),
    uniformAssessmentOn: shortText.nullable(),
    assessorCertificationExpiresOn: shortText.nullable(),
    medicalNecessityConfirmedByLpha: z.boolean(),
  }),
  provider: z.object({
    providerId: shortText,
    credential: z.enum(["LPHA", "QMHP_CS", "CSSP", "PEER_PROVIDER", "FAMILY_PARTNER", "RN"]),
    credentialCurrent: z.boolean(),
    requiredTrainingCurrent: z.boolean(),
    competencyDocumented: z.boolean(),
    employeeOfBillingProvider: z.boolean(),
    supervisionActive: z.boolean(),
    supervisorCredential: z.enum(["LPHA", "QMHP_CS"]).nullable(),
    supervisingQmhpHasLphaSupervision: z.boolean(),
    peerMonthlyMeetingDocumented: z.boolean(),
    peerMonthlyObservationDocumented: z.boolean(),
    familyPartnerCertified: z.boolean(),
  }),
  authorization: z.object({
    status: z.enum(["authorized", "mco_waived", "missing", "pending", "denied"]),
    authorizationId: shortText.nullable(),
    payerModel: z.enum(["managed_care", "fee_for_service"]),
    waiverDocumentationReference: shortText.nullable(),
    validFrom: shortText.nullable(),
    validThrough: shortText.nullable(),
    procedureCode: shortText.nullable(),
    remainingUnits: z.number().finite().nullable(),
  }),
  plan: z.object({
    exists: z.boolean(),
    activeFrom: shortText.nullable(),
    activeThrough: shortText.nullable(),
    serviceIncluded: z.boolean(),
    goalReference: shortText.nullable(),
    typeAmountDurationDocumented: z.boolean(),
    telehealthApproved: z.boolean(),
  }),
  telehealth: z.object({
    consentDocumented: z.boolean(),
    clinicallyAppropriateAndSafe: z.boolean(),
    audioOnlyReason: nullableDetail,
    priorInPersonOrAudiovisualServiceOn: shortText.nullable(),
    rollingTwelveMonthInPersonOrAudiovisualServiceOn: shortText.nullable(),
    rollingTwelveMonthWaiverDocumented: z.boolean(),
  }),
  documentation: z.object({
    personName: nullableDetail,
    diagnosisAndNeed: nullableDetail,
    reasonForEncounter: nullableDetail,
    contactParticipants: nullableDetail,
    collateralContacts: nullableDetail,
    planGoal: nullableDetail,
    progress: nullableDetail,
    serviceAccessTimeline: nullableDetail,
    intervention: nullableDetail,
    reevaluationTimeline: nullableDetail,
    serviceType: nullableDetail,
    modalityAndMethod: nullableDetail,
    location: nullableDetail,
    pertinentEventsOrBehavior: nullableDetail,
    outcomeOrProgress: nullableDetail,
    serviceDate: shortText.nullable(),
    startTime: shortText.nullable(),
    endTime: shortText.nullable(),
    deliveryMode: shortText.nullable(),
    agencyName: nullableDetail,
    providerSignature: nullableDetail,
    providerCredential: nullableDetail,
  }),
  priorEncounters: z.array(z.object({
    encounterId: shortText,
    clientId: shortText,
    serviceDate: shortText,
    startTime: shortText,
    endTime: shortText,
    procedureCode: shortText,
    modifiers: z.array(shortText).max(12),
    status: z.enum(["documented", "submitted", "paid", "voided"]),
  })).max(100),
});

export const part2DataCategorySchema = z.enum([
  "patient_identity",
  "diagnosis",
  "medications",
  "laboratory_results",
  "treatment_plan",
  "progress_summary",
  "billing",
  "sud_counseling_notes",
  "entire_record",
]);

export const part2PurposeSchema = z.enum([
  "treatment",
  "payment",
  "health_care_operations",
  "patient_request",
  "research",
  "fundraising",
  "legal_proceeding",
  "other",
]);

const part2RecordFlagSchema = z.object({
  status: z.enum(["protected", "pending_review"]),
  enforcement: z.literal("treat_as_part2"),
  reasonCodes: z.array(z.enum([
    "PART2_CONFIRMED",
    "PENDING_SUD_CONTENT_REVIEW",
    "PENDING_PART2_PROGRAM_REVIEW",
    "PENDING_FEDERAL_ASSISTANCE_REVIEW",
  ])).max(4),
});

export const part2RecordApplicabilitySchema = z.object({
  containsSudDiagnosisTreatmentOrReferral: z.boolean().optional(),
  maintainedByPart2Program: z.boolean().optional(),
  federallyAssistedProgram: z.boolean().optional(),
});

export const part2AccessSchema = z.object({
  eventId: shortText,
  occurredAt: shortText,
  actorId: shortText,
  patientId: shortText,
  recordId: shortText,
  recordFlag: part2RecordFlagSchema,
  identityVerified: z.boolean(),
  purpose: part2PurposeSchema,
  requestedCategories: z.array(part2DataCategorySchema).max(20),
  authorization: z.object({
    reference: shortText,
    allowedPurposes: z.array(part2PurposeSchema).max(8),
    allowedCategories: z.array(part2DataCategorySchema).max(20),
    pendingReviewAccessApproved: z.boolean().optional(),
    entireRecordJustification: detailText.optional(),
  }).optional(),
});

const part2ConsentSchema = z.object({
  consentId: shortText,
  patientId: shortText,
  patientName: shortText,
  authorizedDisclosers: z.array(shortText).max(50),
  informationDescription: detailText,
  authorizedCategories: z.array(part2DataCategorySchema).max(20),
  recipientDesignation: z.object({
    namesOrClasses: z.array(shortText).max(50),
    intermediary: z.object({
      name: shortText,
      memberParticipants: z.array(shortText).max(100).optional(),
      participantClass: shortText.optional(),
      participantClassLimitedToTreatingProviders: z.boolean().optional(),
    }).optional(),
    coveredEntityOrBusinessAssociateForTpo: z.boolean().optional(),
    hipaaRedisclosureStatementIncluded: z.boolean().optional(),
  }),
  purposeDescription: detailText,
  purposeCodes: z.array(part2PurposeSchema).max(8),
  revocationRightStatement: detailText,
  revocationMethod: detailText,
  expiration: z.discriminatedUnion("kind", [
    z.object({ kind: z.literal("date"), expiresAt: shortText }),
    z.object({ kind: z.literal("event"), description: detailText, occurredAt: shortText.optional() }),
    z.object({ kind: z.literal("none_for_tpo") }),
  ]),
  signature: z.object({
    signerName: shortText,
    signedAt: shortText,
    capacity: z.enum(["patient", "authorized_representative"]),
    authorityReference: shortText.optional(),
  }),
  tpoStatements: z.object({
    potentialRedisclosureStatementIncluded: z.boolean(),
    refusalConsequencesStatementIncluded: z.boolean(),
  }).optional(),
  fundraisingOptOutStatementIncluded: z.boolean().optional(),
  revokedAt: shortText.optional(),
  knownMateriallyFalse: z.boolean().optional(),
});

const part2EmergencySchema = z.object({
  exceptionId: shortText,
  patientId: shortText,
  recordId: shortText,
  disclosureAt: shortText,
  recipientMedicalPersonnelName: shortText,
  recipientAffiliation: shortText,
  disclosedBy: shortText,
  natureOfEmergency: detailText,
  bonaFideMedicalEmergency: z.boolean(),
  priorWrittenConsentCouldNotBeObtained: z.boolean(),
  documentedAt: shortText,
  documentedImmediatelyFollowingDisclosure: z.boolean(),
});

export const part2DisclosureSchema = z.object({
  eventId: shortText,
  occurredAt: shortText,
  actorId: shortText,
  patientId: shortText,
  recordId: shortText,
  recordFlag: part2RecordFlagSchema,
  identityVerified: z.boolean(),
  part2AuthorizationReference: shortText.optional(),
  purpose: part2PurposeSchema,
  requestedCategories: z.array(part2DataCategorySchema).max(20),
  minimumNecessary: z.object({
    policyReference: shortText,
    approvedCategories: z.array(part2DataCategorySchema).max(20),
    entireRecordJustification: detailText.optional(),
  }).optional(),
  recipient: z.object({
    name: shortText,
    designation: shortText,
    type: z.enum([
      "covered_entity",
      "business_associate",
      "part2_program_non_hipaa",
      "non_hipaa_lawful_holder",
      "medical_personnel",
      "other",
    ]),
    address: detailText.optional(),
  }),
  transport: z.enum(["electronic_health_record", "other_electronic", "paper", "oral"]),
  intendedRedisclosure: z.enum([
    "none",
    "hipaa_tpo",
    "consistent_with_consent",
    "contractor_for_payment_or_operations",
    "proceeding_against_patient",
  ]),
  legalBasis: z.discriminatedUnion("type", [
    z.object({
      type: z.literal("written_consent"),
      consent: part2ConsentSchema,
      discloserDesignation: shortText,
      accompaniment: z.object({
        noticeText: detailText,
        consentCopyAttached: z.boolean(),
        clearScopeExplanation: detailText.optional(),
      }).optional(),
    }),
    z.object({ type: z.literal("medical_emergency"), exception: part2EmergencySchema }),
    z.object({ type: z.literal("manual_log"), logReference: shortText.optional() }),
  ]),
});

const groRatioSchema = z.object({
  period: shortText,
  children: z.array(z.object({
    id: shortText,
    ageYears: z.number().finite(),
    requiresTreatmentServices: z.boolean(),
    requiresConstantSupervision: z.boolean().optional(),
    approvedUnsupervisedChildhoodActivity: z.boolean().optional(),
    relationship: z.enum(["child-in-care", "caregiver-child"]).optional(),
  })).max(200),
  caregivers: z.array(z.object({
    id: shortText,
    qualified: z.boolean(),
    workingDirectlyWithGroup: z.boolean(),
    status: shortText,
  })).max(200),
  adultResidentsPresent: z.boolean().optional(),
  setting: z.enum(["cottage-home", "other"]).optional(),
  cottageTemporaryException: z.object({
    forNormalHomeLikeRoutine: z.boolean(),
    shortPeriod: z.boolean(),
    careAndSupervisionNeedsMet: z.boolean(),
    additionalStaffOrCaregiversOnPremisesAndAvailable: z.boolean(),
    addressedInWrittenProfessionalStaffingPlan: z.boolean(),
  }).optional(),
});

const groBedroomSchema = z.object({
  occupantCount: z.number().finite(),
  grossFloorSquareFeet: z.number().finite(),
  closetAndAlcoveSquareFeet: z.number().finite(),
  allOccupantsReceivePrimaryMedicalNeedsTreatment: z.boolean().optional(),
  legacyPermit: z.object({
    grantedBefore2007: z.boolean(),
    emergencyCarePermit: z.boolean(),
    operationMovedSincePermit: z.boolean(),
    bedroomAddedSincePermit: z.boolean(),
    permitStillValid: z.boolean(),
  }).optional(),
});

const groRightsRecipientSchema = z.object({
  reviewedAt: shortText.optional(),
  writtenCopyProvidedAt: shortText.optional(),
  understandsEnglish: z.boolean(),
  primaryLanguageCopyPossible: z.boolean().optional(),
  writtenCopyInPrimaryLanguage: z.boolean().optional(),
  hasVisualOrAuditoryImpairment: z.boolean().optional(),
  accessibleExplanationProvided: z.boolean().optional(),
  acknowledgmentSignedAt: shortText.optional(),
  acknowledgmentConfirmsReadAndUnderstands: z.boolean(),
  acknowledgmentFiledInChildRecord: z.boolean(),
});

const groRightsSchema = z.object({
  admittedAt: shortText,
  rightsDocumentUsesSimpleNonTechnicalTerms: z.boolean(),
  parentConsentRequired: z.boolean(),
  child: groRightsRecipientSchema,
  parent: groRightsRecipientSchema.optional(),
});

const groRestraintSchema = z.object({
  restraintKind: shortText,
  operationPolicyPermits: z.boolean(),
  lessRestrictiveInterventionsAttempted: z.boolean(),
  lessRestrictiveInterventionsIneffective: z.boolean(),
  basis: shortText,
  purpose: shortText,
  minimalReasonableForceUsed: z.boolean(),
  privacyProtected: z.boolean(),
  dignityAndWellBeingProtected: z.boolean(),
  monitor: z.object({
    qualifiedInEmergencyBehaviorIntervention: z.boolean(),
    continuouslyMonitoredAppropriatePerformance: z.boolean(),
    continuouslyMonitoredBreathingAndPhysicalDistress: z.boolean(),
    preparedToProtectRespirationCirculationAndWellBeing: z.boolean(),
  }),
  techniques: z.array(shortText).max(20),
  position: shortText,
  proneOrSupineDurationSeconds: z.number().finite().optional(),
  proneOrSupineWasLastResort: z.boolean().optional(),
  operationCapacity: z.number().finite(),
  independentObserver: z.object({
    present: z.boolean(),
    trainedInPositionalCompressionAndRestraintAsphyxiaRisks: z.boolean(),
    trainedInProneAndSupineRisks: z.boolean(),
    notInvolvedInRestraint: z.boolean(),
  }).optional(),
  childCondition: shortText,
  distressPotentiallyLifeThreatening: z.boolean().optional(),
  releasedImmediately: z.boolean().optional(),
  medicalAssistanceSoughtImmediately: z.boolean().optional(),
  healthCareProfessionalEvaluationDocumentedAt: shortText.optional(),
});

const groPostInterventionSchema = z.object({
  interventionKind: shortText,
  emergencyCareSeclusion: z.boolean().optional(),
  initiatedAt: shortText,
  interventionEndedAt: shortText,
  stabilizedAt: shortText,
  observedUntil: shortText.optional(),
  privateChildDiscussionAt: shortText.optional(),
  caregiverDebriefAt: shortText.optional(),
  caregiverDebriefAsSoonAsPossibleAttested: z.boolean().optional(),
  witnessesPresent: z.boolean().optional(),
  reasonableWitnessDebriefEffortsMade: z.boolean().optional(),
  supervisorReviewedAt: shortText.optional(),
  incidentDocumentedAt: shortText.optional(),
  parentNotifiedInWritingAt: shortText.optional(),
  triggeredReview: z.object({
    triggeredAt: shortText,
    completedAt: shortText.optional(),
    recordsAndOrdersReviewed: z.boolean(),
    medicalAndPsychiatricContraindicationsReviewed: z.boolean(),
    behaviorPatternsAndDeescalationReviewed: z.boolean(),
    alternativesIdentified: z.boolean(),
    writtenReductionPlanCompleted: z.boolean(),
    documentedInChildRecord: z.boolean(),
  }).optional(),
});

const groRetentionSchema = z.object({
  recordType: shortText,
  asOf: shortText,
  investigationStatus: z.enum(["none", "open", "resolved"]),
  investigationResolvedAt: shortText.optional(),
  category: z.enum(["annual-training", "other"]).optional(),
  currentEmployee: z.boolean().optional(),
  trainingYear: z.number().finite().optional(),
  lastDayOfEmployment: shortText.optional(),
  dischargedAt: shortText.optional(),
});

export const groComplianceSchema = z.discriminatedUnion("control", [
  z.object({ control: z.literal("supervision_ratio"), evidence: groRatioSchema }),
  z.object({ control: z.literal("bedroom"), evidence: groBedroomSchema }),
  z.object({ control: z.literal("youth_rights"), evidence: groRightsSchema }),
  z.object({ control: z.literal("practice"), evidence: z.object({ practiceCode: shortText }) }),
  z.object({ control: z.literal("personal_restraint"), evidence: groRestraintSchema }),
  z.object({ control: z.literal("post_intervention"), evidence: groPostInterventionSchema }),
  z.object({ control: z.literal("record_retention"), evidence: groRetentionSchema }),
]);
