/**
 * AMOS-OPS Forms Registry Seed Script
 * Populates the form_templates, form_template_fields, and form_role_bindings tables
 * with all 55 forms defined in the HR Lifecycle Binder taxonomy.
 */

import { drizzle } from "drizzle-orm/better-sqlite3";
import Database from "better-sqlite3";
import * as schema from "./schema";
import { formTemplates, formTemplateFields, formRoleBindings } from "./schema";
import { randomUUID } from "crypto";
import { assertSyntheticSeedAllowed } from "./seed-guard";

const formsDatabasePath = process.env.DATABASE_PATH ?? "amos-ops-evaluation-forms.db";
assertSyntheticSeedAllowed({
  scriptName: "db/seed-forms.ts",
  databasePath: formsDatabasePath,
});
const client = new Database(formsDatabasePath);
const db = drizzle(client, { schema });

// ─── Form Definitions ────────────────────────────────────────

interface FormDef {
  formCode: string;
  name: string;
  description?: string;
  binderArea: string;
  binderAreaIndex: number;
  lifecycleModule?: string;
  requiredForGate: boolean;
  signatureRequired: boolean;
  reviewerRequired: boolean;
  outputFormat: "pdf" | "docx";
  retentionCategory?: string;
  renewalRule?: string;
  fields: Array<{
    name: string;
    label: string;
    fieldType: "text" | "textarea" | "date" | "checkbox" | "select" | "multiselect" | "number" | "email" | "phone" | "signature" | "initials" | "file";
    required: boolean;
    section?: string;
    options?: string[];
  }>;
  roleBindings: Array<{
    role: string;
    isRequired: boolean;
    isAutoAssigned: boolean;
    assignmentTrigger: string;
    dueDays: number;
  }>;
}

const FORMS: FormDef[] = [
  // ─── 00 - Master Control ───────────────────────────────────
  {
    formCode: "FR-00.01",
    name: "Employee HR Binder Master Control Sheet",
    description: "Master control cover sheet for the employee HR binder. Lists all binder sections and form codes.",
    binderArea: "00_Master_Control",
    binderAreaIndex: 0,
    requiredForGate: false,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Header" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Header" },
      { name: "hireDate", label: "Hire Date", fieldType: "date", required: true, section: "Header" },
      { name: "department", label: "Department", fieldType: "select", required: true, options: ["Field Operations", "Human Resources", "Clinical", "Quality Assurance", "Operations", "Training", "Compliance", "Executive"], section: "Header" },
      { name: "binderCheckedBy", label: "Binder Checked By", fieldType: "text", required: false, section: "Verification" },
      { name: "binderCheckDate", label: "Binder Check Date", fieldType: "date", required: false, section: "Verification" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-create", dueDays: 1 },
      { role: "training-coordinator", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
    ],
  },
  {
    formCode: "FR-00.02",
    name: "HR Binder Section Checklist",
    description: "Tracks completion of all 15 binder sections per employee.",
    binderArea: "00_Master_Control",
    binderAreaIndex: 0,
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "section01Complete", label: "01 Recruitment Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section02Complete", label: "02 Conditional Offer Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section03Complete", label: "03 Pre-Employment Clearance Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section04Complete", label: "04 Screening Clearance Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section05Complete", label: "05 Final Agreement Clearance Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section06Complete", label: "06 Orientation Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section07Complete", label: "07 Training Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section08Complete", label: "08 GRO Assignment Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section09Complete", label: "09 Benefits Enrollment Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section10Complete", label: "10 Performance Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section11Complete", label: "11 Separation Complete", fieldType: "checkbox", required: false, section: "Sections" },
      { name: "section12Complete", label: "12 Grievance Complete", fieldType: "checkbox", required: false, section: "Sections" },
      { name: "section13Complete", label: "13 File Management Complete", fieldType: "checkbox", required: true, section: "Sections" },
      { name: "section14Complete", label: "14 Audit Logs Complete", fieldType: "checkbox", required: false, section: "Sections" },
      { name: "verifiedBy", label: "Verified By (HR Director)", fieldType: "text", required: true, section: "Verification" },
      { name: "verificationDate", label: "Verification Date", fieldType: "date", required: true, section: "Verification" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 30 },
    ],
  },

  // ─── 01 - Recruitment ──────────────────────────────────────
  {
    formCode: "FR-01.01",
    name: "Job Requisition Form",
    description: "Initiates the recruitment process. Approved by department head and HR.",
    binderArea: "01_Recruitment",
    binderAreaIndex: 1,
    lifecycleModule: "recruitment",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "positionTitle", label: "Position Title", fieldType: "text", required: true, section: "Position" },
      { name: "department", label: "Department", fieldType: "select", required: true, options: ["Field Operations", "Human Resources", "Clinical", "Quality Assurance", "Operations", "Training", "Compliance", "Executive"], section: "Position" },
      { name: "requestedBy", label: "Requested By", fieldType: "text", required: true, section: "Request" },
      { name: "requestDate", label: "Request Date", fieldType: "date", required: true, section: "Request" },
      { name: "justification", label: "Business Justification", fieldType: "textarea", required: true, section: "Request" },
      { name: "budgetApproved", label: "Budget Approved", fieldType: "checkbox", required: true, section: "Approval" },
      { name: "deptHeadSignature", label: "Department Head Signature", fieldType: "signature", required: true, section: "Approval" },
      { name: "hrApprovalSignature", label: "HR Approval Signature", fieldType: "signature", required: true, section: "Approval" },
    ],
    roleBindings: [
      { role: "facilities-manager", isRequired: true, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 7 },
      { role: "hr-director", isRequired: true, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 7 },
    ],
  },
  {
    formCode: "FR-01.02",
    name: "Candidate Application",
    description: "Standard employment application form for all candidates.",
    binderArea: "01_Recruitment",
    binderAreaIndex: 1,
    lifecycleModule: "recruitment",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "lastName", label: "Last Name", fieldType: "text", required: true, section: "Personal" },
      { name: "firstName", label: "First Name", fieldType: "text", required: true, section: "Personal" },
      { name: "ssn", label: "SSN (Last 4)", fieldType: "text", required: true, section: "Personal" },
      { name: "dateOfBirth", label: "Date of Birth", fieldType: "date", required: true, section: "Personal" },
      { name: "address", label: "Street Address", fieldType: "textarea", required: true, section: "Contact" },
      { name: "city", label: "City", fieldType: "text", required: true, section: "Contact" },
      { name: "state", label: "State", fieldType: "select", required: true, options: ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"], section: "Contact" },
      { name: "zip", label: "ZIP Code", fieldType: "text", required: true, section: "Contact" },
      { name: "phone", label: "Phone Number", fieldType: "phone", required: true, section: "Contact" },
      { name: "email", label: "Email Address", fieldType: "email", required: true, section: "Contact" },
      { name: "positionApplied", label: "Position Applied For", fieldType: "text", required: true, section: "Employment" },
      { name: "availableStart", label: "Available Start Date", fieldType: "date", required: true, section: "Employment" },
      { name: "desiredSalary", label: "Desired Salary", fieldType: "text", required: false, section: "Employment" },
      { name: "legallyAuthorized", label: "Legally authorized to work in US?", fieldType: "select", required: true, options: ["Yes", "No"], section: "Eligibility" },
      { name: "felonyConviction", label: "Ever convicted of a felony?", fieldType: "select", required: true, options: ["Yes", "No"], section: "Eligibility" },
      { name: "felonyExplanation", label: "If yes, explain", fieldType: "textarea", required: false, section: "Eligibility" },
      { name: "educationLevel", label: "Highest Education Level", fieldType: "select", required: true, options: ["High School/GED", "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate", "Other"], section: "Education" },
      { name: "signature", label: "Applicant Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "signatureDate", label: "Date", fieldType: "date", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-create", dueDays: 7 },
    ],
  },
  {
    formCode: "FR-01.03",
    name: "Interview Evaluation Sheet",
    description: "Standardized evaluation for all candidate interviews.",
    binderArea: "01_Recruitment",
    binderAreaIndex: 1,
    lifecycleModule: "recruitment",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Interview" },
      { name: "interviewDate", label: "Interview Date", fieldType: "date", required: true, section: "Interview" },
      { name: "interviewerName", label: "Interviewer Name/Title", fieldType: "text", required: true, section: "Interview" },
      { name: "position", label: "Position Interviewed For", fieldType: "text", required: true, section: "Interview" },
      { name: "jobKnowledge", label: "Job Knowledge (1-5)", fieldType: "select", required: true, options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"], section: "Ratings" },
      { name: "communication", label: "Communication Skills (1-5)", fieldType: "select", required: true, options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"], section: "Ratings" },
      { name: "professionalism", label: "Professionalism (1-5)", fieldType: "select", required: true, options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"], section: "Ratings" },
      { name: "culturalFit", label: "Cultural Fit (1-5)", fieldType: "select", required: true, options: ["1 - Poor", "2 - Fair", "3 - Good", "4 - Very Good", "5 - Excellent"], section: "Ratings" },
      { name: "overallRating", label: "Overall Rating", fieldType: "select", required: true, options: ["Do Not Hire", "Below Average", "Average", "Above Average", "Excellent - Hire"], section: "Recommendation" },
      { name: "recommendation", label: "Detailed Recommendation", fieldType: "textarea", required: true, section: "Recommendation" },
      { name: "interviewerSignature", label: "Interviewer Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "interviewDate2", label: "Date", fieldType: "date", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 3 },
      { role: "clinical-director", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 3 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 7 },
    ],
  },
  {
    formCode: "FR-01.04",
    name: "Reference Check Log",
    description: "Logs all reference checks conducted for a candidate.",
    binderArea: "01_Recruitment",
    binderAreaIndex: 1,
    lifecycleModule: "recruitment",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Candidate" },
      { name: "reference1Name", label: "Reference 1 - Name", fieldType: "text", required: true, section: "References" },
      { name: "reference1Relationship", label: "Relationship", fieldType: "text", required: true, section: "References" },
      { name: "reference1Phone", label: "Phone", fieldType: "phone", required: true, section: "References" },
      { name: "reference1Date", label: "Date Contacted", fieldType: "date", required: true, section: "References" },
      { name: "reference1Notes", label: "Notes", fieldType: "textarea", required: true, section: "References" },
      { name: "reference2Name", label: "Reference 2 - Name", fieldType: "text", required: true, section: "References" },
      { name: "reference2Relationship", label: "Relationship", fieldType: "text", required: true, section: "References" },
      { name: "reference2Phone", label: "Phone", fieldType: "phone", required: true, section: "References" },
      { name: "reference2Date", label: "Date Contacted", fieldType: "date", required: true, section: "References" },
      { name: "reference2Notes", label: "Notes", fieldType: "textarea", required: true, section: "References" },
      { name: "completedBy", label: "Completed By", fieldType: "text", required: true, section: "Verification" },
      { name: "completionDate", label: "Completion Date", fieldType: "date", required: true, section: "Verification" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:recruitment", dueDays: 14 },
    ],
  },

  // ─── 02 - Conditional Offer ────────────────────────────────
  {
    formCode: "FR-02.01",
    name: "Conditional Offer Letter",
    description: "Formal conditional offer letter with acceptance signature.",
    binderArea: "02_Conditional_Offer",
    binderAreaIndex: 2,
    lifecycleModule: "conditional-offer",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "candidateName", label: "Candidate Full Name", fieldType: "text", required: true, section: "Offer" },
      { name: "positionTitle", label: "Position Title", fieldType: "text", required: true, section: "Offer" },
      { name: "department", label: "Department", fieldType: "select", required: true, options: ["Field Operations", "Human Resources", "Clinical", "Quality Assurance", "Operations", "Training", "Compliance", "Executive"], section: "Offer" },
      { name: "startDate", label: "Proposed Start Date", fieldType: "date", required: true, section: "Offer" },
      { name: "salary", label: "Annual Salary / Hourly Rate", fieldType: "text", required: true, section: "Compensation" },
      { name: "employmentType", label: "Employment Type", fieldType: "select", required: true, options: ["Full-Time", "Part-Time", "Contract", "Temporary"], section: "Compensation" },
      { name: "conditions", label: "Conditions of Employment", fieldType: "textarea", required: true, section: "Conditions" },
      { name: "candidateAccepts", label: "Candidate Accepts Offer", fieldType: "select", required: true, options: ["Yes", "No"], section: "Acceptance" },
      { name: "candidateSignature", label: "Candidate Signature", fieldType: "signature", required: true, section: "Acceptance" },
      { name: "acceptanceDate", label: "Acceptance Date", fieldType: "date", required: true, section: "Acceptance" },
      { name: "hrDirectorSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Authorization" },
      { name: "hrDate", label: "Date", fieldType: "date", required: true, section: "Authorization" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:conditional-offer", dueDays: 7 },
    ],
  },
  {
    formCode: "FR-02.02",
    name: "Background Check Authorization",
    description: "Consent form for criminal background check. Required by law.",
    binderArea: "02_Conditional_Offer",
    binderAreaIndex: 2,
    lifecycleModule: "conditional-offer",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "candidateName", label: "Full Legal Name", fieldType: "text", required: true, section: "Identity" },
      { name: "ssnFull", label: "Social Security Number", fieldType: "text", required: true, section: "Identity" },
      { name: "dateOfBirth", label: "Date of Birth", fieldType: "date", required: true, section: "Identity" },
      { name: "currentAddress", label: "Current Address", fieldType: "textarea", required: true, section: "Identity" },
      { name: "previousAddresses", label: "Previous Addresses (5 years)", fieldType: "textarea", required: true, section: "Identity" },
      { name: "aliasNames", label: "Other Names Used (Alias/Maiden)", fieldType: "text", required: false, section: "Identity" },
      { name: "consentGiven", label: "I authorize a background check", fieldType: "checkbox", required: true, section: "Consent" },
      { name: "consumerRightsAck", label: "I acknowledge receipt of FCRA rights", fieldType: "checkbox", required: true, section: "Consent" },
      { name: "candidateSignature", label: "Candidate Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "signatureDate", label: "Date", fieldType: "date", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:conditional-offer", dueDays: 3 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:conditional-offer", dueDays: 5 },
    ],
  },

  // ─── 03 - Pre-Employment Clearance ─────────────────────────
  {
    formCode: "FR-03.01",
    name: "Drug Test Consent & Results",
    description: "Chain of custody form for pre-employment drug screening.",
    binderArea: "03_Pre_Employment_Clearance",
    binderAreaIndex: 3,
    lifecycleModule: "pre-employment-clearance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Identity" },
      { name: "employeeId", label: "Employee ID (if assigned)", fieldType: "text", required: false, section: "Identity" },
      { name: "collectionDate", label: "Specimen Collection Date", fieldType: "date", required: true, section: "Collection" },
      { name: "collectionTime", label: "Collection Time", fieldType: "text", required: true, section: "Collection" },
      { name: "collectorName", label: "Collector Name", fieldType: "text", required: true, section: "Collection" },
      { name: "candidateConsent", label: "Candidate Consent Given", fieldType: "checkbox", required: true, section: "Consent" },
      { name: "candidateSignature", label: "Candidate Signature", fieldType: "signature", required: true, section: "Consent" },
      { name: "resultStatus", label: "Test Result", fieldType: "select", required: true, options: ["Negative", "Positive", "Pending", "Refused"], section: "Results" },
      { name: "resultDate", label: "Result Date", fieldType: "date", required: true, section: "Results" },
      { name: "labName", label: "Testing Laboratory", fieldType: "text", required: true, section: "Results" },
      { name: "medicalOfficer", label: "Medical Review Officer", fieldType: "text", required: true, section: "Results" },
      { name: "hrAcknowledgment", label: "HR Acknowledgment", fieldType: "signature", required: true, section: "HR" },
      { name: "hrDate", label: "HR Date", fieldType: "date", required: true, section: "HR" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:pre-employment-clearance", dueDays: 5 },
    ],
  },
  {
    formCode: "FR-03.02",
    name: "Medical Clearance Form",
    description: "Medical examination clearance from licensed physician.",
    binderArea: "03_Pre_Employment_Clearance",
    binderAreaIndex: 3,
    lifecycleModule: "pre-employment-clearance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Candidate" },
      { name: "examDate", label: "Examination Date", fieldType: "date", required: true, section: "Examination" },
      { name: "physicianName", label: "Physician Name", fieldType: "text", required: true, section: "Physician" },
      { name: "physicianLicense", label: "Physician License #", fieldType: "text", required: true, section: "Physician" },
      { name: "fitForDuty", label: "Fit for Duty?", fieldType: "select", required: true, options: ["Yes - No Restrictions", "Yes - With Restrictions", "No - Not Cleared"], section: "Determination" },
      { name: "restrictions", label: "If restrictions, describe", fieldType: "textarea", required: false, section: "Determination" },
      { name: "tbTestResult", label: "TB Test Result", fieldType: "select", required: true, options: ["Negative", "Positive", "Pending"], section: "Tests" },
      { name: "tbTestDate", label: "TB Test Date", fieldType: "date", required: true, section: "Tests" },
      { name: "immunizationCurrent", label: "Immunizations Current?", fieldType: "select", required: true, options: ["Yes", "No - See Notes"], section: "Tests" },
      { name: "physicianSignature", label: "Physician Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "physicianDate", label: "Date", fieldType: "date", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "clinical-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:pre-employment-clearance", dueDays: 10 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:pre-employment-clearance", dueDays: 14 },
    ],
  },

  // ─── 04 - Screening Clearance ──────────────────────────────
  {
    formCode: "FR-04.01",
    name: "Fingerprinting & Criminal Record Check",
    description: "LiveScan fingerprinting and state/federal criminal record verification.",
    binderArea: "04_Screening_Clearance",
    binderAreaIndex: 4,
    lifecycleModule: "screening-clearance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Identity" },
      { name: " LivescanDate", label: "LiveScan Date", fieldType: "date", required: true, section: "Fingerprinting" },
      { name: " LivescanVendor", label: "LiveScan Vendor", fieldType: "text", required: true, section: "Fingerprinting" },
      { name: " LivescanTcn", label: "Transaction Control Number (TCN)", fieldType: "text", required: true, section: "Fingerprinting" },
      { name: "stateCheckResult", label: "State Criminal Check", fieldType: "select", required: true, options: ["Clear", "Record Found", "Pending"], section: "Results" },
      { name: "federalCheckResult", label: "Federal Criminal Check", fieldType: "select", required: true, options: ["Clear", "Record Found", "Pending"], section: "Results" },
      { name: "meganCheckResult", label: "MEGAN'S LAW Check", fieldType: "select", required: true, options: ["Clear", "Record Found", "Pending"], section: "Results" },
      { name: "sexOffenderCheck", label: "Sex Offender Registry", fieldType: "select", required: true, options: ["Clear", "Record Found", "Pending"], section: "Results" },
      { name: "overallClearance", label: "Overall Clearance Status", fieldType: "select", required: true, options: ["Cleared", "Conditional", "Denied"], section: "Results" },
      { name: "hrDirectorSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "HR" },
      { name: "hrDate", label: "Date", fieldType: "date", required: true, section: "HR" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:screening-clearance", dueDays: 14 },
    ],
  },
  {
    formCode: "FR-04.02",
    name: "Child Abuse Clearance (CAC)",
    description: "Pennsylvania Child Abuse History Clearance certification.",
    binderArea: "04_Screening_Clearance",
    binderAreaIndex: 4,
    lifecycleModule: "screening-clearance",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Identity" },
      { name: "cacApplicationDate", label: "CAC Application Date", fieldType: "date", required: true, section: "Application" },
      { name: "cacCertificateNumber", label: "CAC Certificate Number", fieldType: "text", required: true, section: "Certificate" },
      { name: "cacIssueDate", label: "CAC Issue Date", fieldType: "date", required: true, section: "Certificate" },
      { name: "cacResult", label: "CAC Result", fieldType: "select", required: true, options: ["No Record", "Record Found - See Notes", "Pending"], section: "Certificate" },
      { name: "cacExpiration", label: "CAC Expiration Date", fieldType: "date", required: true, section: "Certificate" },
      { name: "renewalDue", label: "Renewal Due (5 years)", fieldType: "date", required: false, section: "Renewal" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:screening-clearance", dueDays: 14 },
    ],
  },
  {
    formCode: "FR-04.03",
    name: "FBI Criminal Background Check",
    description: "Federal Bureau of Investigation background check for direct-care positions.",
    binderArea: "04_Screening_Clearance",
    binderAreaIndex: 4,
    lifecycleModule: "screening-clearance",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "candidateName", label: "Candidate Name", fieldType: "text", required: true, section: "Identity" },
      { name: "fbiSubmissionDate", label: "FBI Submission Date", fieldType: "date", required: true, section: "Submission" },
      { name: "fbiResultDate", label: "FBI Result Date", fieldType: "date", required: true, section: "Results" },
      { name: "fbiStatus", label: "FBI Check Status", fieldType: "select", required: true, options: ["Clear", "Record Found", "Pending"], section: "Results" },
      { name: "disposition", label: "Disposition", fieldType: "select", required: true, options: ["Cleared for Hire", "Cleared with Conditions", "Not Cleared"], section: "Results" },
      { name: "hrSignature", label: "HR Director Verification", fieldType: "signature", required: true, section: "Verification" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:screening-clearance", dueDays: 21 },
    ],
  },

  // ─── 05 - Final Agreement Clearance ────────────────────────
  {
    formCode: "FR-05.01",
    name: "Employment Agreement",
    description: "Final employment contract signed by employee and HR Director.",
    binderArea: "05_Final_Agreement_Clearance",
    binderAreaIndex: 5,
    lifecycleModule: "final-agreement-clearance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "employeeName", label: "Employee Full Name", fieldType: "text", required: true, section: "Employee" },
      { name: "positionTitle", label: "Position Title", fieldType: "text", required: true, section: "Employment" },
      { name: "department", label: "Department", fieldType: "select", required: true, options: ["Field Operations", "Human Resources", "Clinical", "Quality Assurance", "Operations", "Training", "Compliance", "Executive"], section: "Employment" },
      { name: "startDate", label: "Employment Start Date", fieldType: "date", required: true, section: "Employment" },
      { name: "salaryWage", label: "Salary / Wage", fieldType: "text", required: true, section: "Compensation" },
      { name: "paySchedule", label: "Pay Schedule", fieldType: "select", required: true, options: ["Bi-Weekly", "Semi-Monthly", "Monthly"], section: "Compensation" },
      { name: "atWillAck", label: "At-Will Employment Acknowledged", fieldType: "checkbox", required: true, section: "Terms" },
      { name: "confidentialityAck", label: "Confidentiality Agreement Acknowledged", fieldType: "checkbox", required: true, section: "Terms" },
      { name: "handbookAck", label: "Employee Handbook Received & Acknowledged", fieldType: "checkbox", required: true, section: "Terms" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "employeeDate", label: "Date", fieldType: "date", required: true, section: "Signatures" },
      { name: "hrDirectorSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "hrDate", label: "Date", fieldType: "date", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:final-agreement-clearance", dueDays: 3 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:final-agreement-clearance", dueDays: 5 },
    ],
  },
  {
    formCode: "FR-05.02",
    name: "Direct Deposit Authorization",
    description: "Banking information for payroll direct deposit.",
    binderArea: "05_Final_Agreement_Clearance",
    binderAreaIndex: 5,
    lifecycleModule: "final-agreement-clearance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "bankName", label: "Bank Name", fieldType: "text", required: true, section: "Bank" },
      { name: "accountType", label: "Account Type", fieldType: "select", required: true, options: ["Checking", "Savings"], section: "Bank" },
      { name: "routingNumber", label: "Routing Number", fieldType: "text", required: true, section: "Bank" },
      { name: "accountNumber", label: "Account Number", fieldType: "text", required: true, section: "Bank" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Authorization" },
      { name: "date", label: "Date", fieldType: "date", required: true, section: "Authorization" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:final-agreement-clearance", dueDays: 3 },
    ],
  },
  {
    formCode: "FR-05.03",
    name: "Emergency Contact & Next of Kin",
    description: "Primary and secondary emergency contact information.",
    binderArea: "05_Final_Agreement_Clearance",
    binderAreaIndex: 5,
    lifecycleModule: "final-agreement-clearance",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "ec1Name", label: "Primary Contact Name", fieldType: "text", required: true, section: "Primary Contact" },
      { name: "ec1Relationship", label: "Relationship", fieldType: "text", required: true, section: "Primary Contact" },
      { name: "ec1Phone", label: "Phone", fieldType: "phone", required: true, section: "Primary Contact" },
      { name: "ec1Address", label: "Address", fieldType: "textarea", required: true, section: "Primary Contact" },
      { name: "ec2Name", label: "Secondary Contact Name", fieldType: "text", required: false, section: "Secondary Contact" },
      { name: "ec2Relationship", label: "Relationship", fieldType: "text", required: false, section: "Secondary Contact" },
      { name: "ec2Phone", label: "Phone", fieldType: "phone", required: false, section: "Secondary Contact" },
      { name: "medicalInfo", label: "Medical Conditions / Allergies", fieldType: "textarea", required: false, section: "Medical" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:final-agreement-clearance", dueDays: 1 },
    ],
  },
  {
    formCode: "FR-05.04",
    name: "Tax Forms (W-4 / State)",
    description: "Federal W-4 and state tax withholding forms.",
    binderArea: "05_Final_Agreement_Clearance",
    binderAreaIndex: 5,
    lifecycleModule: "final-agreement-clearance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "W-4" },
      { name: "ssn", label: "Social Security Number", fieldType: "text", required: true, section: "W-4" },
      { name: "address", label: "Home Address", fieldType: "textarea", required: true, section: "W-4" },
      { name: "filingStatus", label: "Filing Status", fieldType: "select", required: true, options: ["Single", "Married filing jointly", "Married filing separately", "Head of household"], section: "W-4" },
      { name: "allowances", label: "Total Allowances", fieldType: "number", required: true, section: "W-4" },
      { name: "additionalWithholding", label: "Additional Withholding", fieldType: "text", required: false, section: "W-4" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "W-4" },
      { name: "date", label: "Date", fieldType: "date", required: true, section: "W-4" },
      { name: "stateTaxForm", label: "State Tax Form Completed", fieldType: "checkbox", required: true, section: "State" },
      { name: "stateFormType", label: "State Form Type", fieldType: "text", required: true, section: "State" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:final-agreement-clearance", dueDays: 1 },
    ],
  },
  {
    formCode: "FR-05.05",
    name: "E-Verify Confirmation",
    description: "Federal employment eligibility verification via E-Verify.",
    binderArea: "05_Final_Agreement_Clearance",
    binderAreaIndex: 5,
    lifecycleModule: "final-agreement-clearance",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "caseNumber", label: "E-Verify Case Number", fieldType: "text", required: true, section: "Verification" },
      { name: "verifyDate", label: "E-Verify Date", fieldType: "date", required: true, section: "Verification" },
      { name: "verifyResult", label: "E-Verify Result", fieldType: "select", required: true, options: ["Employment Authorized", "Tentative Nonconfirmation (TNC)", "Case in Continuance", "Final Nonconfirmation"], section: "Verification" },
      { name: "photoMatch", label: "Photo Match", fieldType: "select", required: true, options: ["Photo Match", "Photo Not Available", "Photo Does Not Match"], section: "Verification" },
      { name: "hrInitials", label: "HR Initials", fieldType: "text", required: true, section: "HR" },
      { name: "hrDate", label: "HR Date", fieldType: "date", required: true, section: "HR" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:final-agreement-clearance", dueDays: 3 },
    ],
  },

  // ─── 06 - Orientation ──────────────────────────────────────
  {
    formCode: "FR-06.01",
    name: "Orientation Checklist",
    description: "Checklist of all orientation topics covered with employee.",
    binderArea: "06_Orientation",
    binderAreaIndex: 6,
    lifecycleModule: "orientation",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "orientationDate", label: "Orientation Date", fieldType: "date", required: true, section: "Header" },
      { name: "facilityTour", label: "Facility Tour Completed", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "safetyTraining", label: "Safety & Emergency Procedures", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "hipaaTraining", label: "HIPAA / Privacy Training", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "abuseReporting", label: "Abuse & Neglect Reporting", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "clientRights", label: "Client Rights Overview", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "emergencyProcedures", label: "Emergency Response Procedures", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "codeOfConduct", label: "Code of Conduct Review", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "attendancePolicy", label: "Attendance & PTO Policy", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "dressCode", label: "Dress Code Policy", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "communicationPolicy", label: "Communication & Social Media Policy", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "incidentReporting", label: "Incident Reporting Procedures", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "technologyUse", label: "Technology & Device Use Policy", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "employeeQuestions", label: "Employee Questions Answered", fieldType: "checkbox", required: true, section: "Topics" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "employeeDate", label: "Date", fieldType: "date", required: true, section: "Signatures" },
      { name: "orienterName", label: "Orienter Name", fieldType: "text", required: true, section: "Signatures" },
      { name: "orienterSignature", label: "Orienter Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "orienterDate", label: "Date", fieldType: "date", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "training-coordinator", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:orientation", dueDays: 1 },
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:orientation", dueDays: 1 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:orientation", dueDays: 3 },
    ],
  },
  {
    formCode: "FR-06.02",
    name: "Employee Handbook Acknowledgment",
    description: "Signed acknowledgment that employee received and read the handbook.",
    binderArea: "06_Orientation",
    binderAreaIndex: 6,
    lifecycleModule: "orientation",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "handbookReceived", label: "Employee Handbook Received", fieldType: "checkbox", required: true, section: "Acknowledgment" },
      { name: "policiesReviewed", label: "All Policies Reviewed", fieldType: "checkbox", required: true, section: "Acknowledgment" },
      { name: "questionsAnswered", label: "All Questions Answered", fieldType: "checkbox", required: true, section: "Acknowledgment" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "date", label: "Date", fieldType: "date", required: true, section: "Signature" },
      { name: "hrWitness", label: "HR Witness", fieldType: "text", required: true, section: "Witness" },
      { name: "hrWitnessDate", label: "Date", fieldType: "date", required: true, section: "Witness" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:orientation", dueDays: 1 },
    ],
  },

  // ─── 07 - Training ─────────────────────────────────────────
  {
    formCode: "FR-07.01",
    name: "Mandated Reporter Training Certificate",
    description: "Certificate of completion for mandated reporter training.",
    binderArea: "07_Training",
    binderAreaIndex: 7,
    lifecycleModule: "training",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "trainingProvider", label: "Training Provider", fieldType: "text", required: true, section: "Training" },
      { name: "completionDate", label: "Completion Date", fieldType: "date", required: true, section: "Training" },
      { name: "certificateNumber", label: "Certificate Number", fieldType: "text", required: true, section: "Certificate" },
      { name: "expirationDate", label: "Expiration Date", fieldType: "date", required: true, section: "Certificate" },
      { name: "hoursCompleted", label: "Hours Completed", fieldType: "number", required: true, section: "Training" },
      { name: "trainingCoordinatorSignature", label: "Training Coordinator Signature", fieldType: "signature", required: true, section: "Verification" },
    ],
    roleBindings: [
      { role: "training-coordinator", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:training", dueDays: 5 },
    ],
  },
  {
    formCode: "FR-07.02",
    name: "CPI / Safety Intervention Training",
    description: "Crisis Prevention Institute training for physical intervention.",
    binderArea: "07_Training",
    binderAreaIndex: 7,
    lifecycleModule: "training",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "cpiLevel", label: "CPI Training Level", fieldType: "select", required: true, options: ["Nonviolent Crisis Intervention", "Blue Card", "Instructor Certification"], section: "Training" },
      { name: "completionDate", label: "Completion Date", fieldType: "date", required: true, section: "Training" },
      { name: "instructorName", label: "Instructor Name", fieldType: "text", required: true, section: "Training" },
      { name: "expirationDate", label: "Expiration Date (Annual)", fieldType: "date", required: true, section: "Certificate" },
      { name: "certificateNumber", label: "Certificate #", fieldType: "text", required: true, section: "Certificate" },
      { name: "trainingCoordinatorSignature", label: "Training Coordinator Verification", fieldType: "signature", required: true, section: "Verification" },
    ],
    roleBindings: [
      { role: "training-coordinator", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:training", dueDays: 14 },
    ],
  },
  {
    formCode: "FR-07.03",
    name: "First Aid / CPR / AED Certification",
    description: "American Heart Association or Red Cross CPR/First Aid certification.",
    binderArea: "07_Training",
    binderAreaIndex: 7,
    lifecycleModule: "training",
    requiredForGate: true,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    renewalRule: "R2 - Renew Every 2 Years",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "certificationType", label: "Certification Type", fieldType: "select", required: true, options: ["Heartsaver CPR/AED", "BLS Provider", "First Aid"], section: "Certificate" },
      { name: "issuingOrganization", label: "Issuing Organization", fieldType: "select", required: true, options: ["American Heart Association", "American Red Cross", "Other"], section: "Certificate" },
      { name: "issueDate", label: "Issue Date", fieldType: "date", required: true, section: "Certificate" },
      { name: "expirationDate", label: "Expiration Date", fieldType: "date", required: true, section: "Certificate" },
      { name: "instructorName", label: "Instructor Name", fieldType: "text", required: true, section: "Certificate" },
      { name: "credentialCoordinatorSignature", label: "Credential Coordinator Signature", fieldType: "signature", required: true, section: "Verification" },
    ],
    roleBindings: [
      { role: "training-coordinator", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:training", dueDays: 14 },
    ],
  },
  {
    formCode: "FR-07.04",
    name: "GRO Core Curriculum Completion",
    description: "Signed roster confirming completion of all GRO core training modules.",
    binderArea: "07_Training",
    binderAreaIndex: 7,
    lifecycleModule: "training",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "module01", label: "Module 1: GRO Overview", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module02", label: "Module 2: Client Care Standards", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module03", label: "Module 3: Behavior Support Plans", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module04", label: "Module 4: Documentation Requirements", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module05", label: "Module 5: Medication Administration", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module06", label: "Module 6: Emergency Procedures", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module07", label: "Module 7: De-escalation Techniques", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module08", label: "Module 8: Incident Reporting", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module09", label: "Module 9: Client Rights & Advocacy", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "module10", label: "Module 10: Cultural Competency", fieldType: "checkbox", required: true, section: "Modules" },
      { name: "competencyAssessment", label: "Competency Assessment Passed", fieldType: "checkbox", required: true, section: "Assessment" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "employeeDate", label: "Date", fieldType: "date", required: true, section: "Signatures" },
      { name: "trainingCoordinatorSignature", label: "Training Coordinator Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:training", dueDays: 30 },
      { role: "training-coordinator", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:training", dueDays: 30 },
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:training", dueDays: 30 },
    ],
  },

  // ─── 08 - GRO Assignment ───────────────────────────────────
  {
    formCode: "FR-08.01",
    name: "GRO Work Assignment Agreement",
    description: "Signed agreement outlining GRO-specific responsibilities.",
    binderArea: "08_GRO_Assignment",
    binderAreaIndex: 8,
    lifecycleModule: "gro-assignment",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "assignmentDate", label: "Assignment Date", fieldType: "date", required: true, section: "Assignment" },
      { name: "workLocation", label: "Work Location / Facility", fieldType: "text", required: true, section: "Assignment" },
      { name: "shift", label: "Shift", fieldType: "select", required: true, options: ["Day", "Evening", "Night", "Weekend"], section: "Assignment" },
      { name: "clientPopulation", label: "Client Population", fieldType: "select", required: true, options: ["Adult DD", "Adult MI", "Children & Youth", "Autism"], section: "Assignment" },
      { name: "responsibilitiesAck", label: "Responsibilities Acknowledged", fieldType: "checkbox", required: true, section: "Acknowledgment" },
      { name: "supervisorName", label: "Supervisor Name", fieldType: "text", required: true, section: "Supervisor" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "employeeDate", label: "Date", fieldType: "date", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:gro-assignment", dueDays: 3 },
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:gro-assignment", dueDays: 3 },
    ],
  },
  {
    formCode: "FR-08.02",
    name: "Client Assignment Roster",
    description: "Lists the clients assigned to this GRO employee.",
    binderArea: "08_GRO_Assignment",
    binderAreaIndex: 8,
    lifecycleModule: "gro-assignment",
    requiredForGate: false,
    signatureRequired: false,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "GRO Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "client1Name", label: "Client 1 - Name", fieldType: "text", required: false, section: "Clients" },
      { name: "client1Id", label: "Client 1 - ID", fieldType: "text", required: false, section: "Clients" },
      { name: "client2Name", label: "Client 2 - Name", fieldType: "text", required: false, section: "Clients" },
      { name: "client2Id", label: "Client 2 - ID", fieldType: "text", required: false, section: "Clients" },
      { name: "client3Name", label: "Client 3 - Name", fieldType: "text", required: false, section: "Clients" },
      { name: "client3Id", label: "Client 3 - ID", fieldType: "text", required: false, section: "Clients" },
      { name: "effectiveDate", label: "Effective Date", fieldType: "date", required: true, section: "Header" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: false, isAutoAssigned: true, assignmentTrigger: "on-module-entry:gro-assignment", dueDays: 7 },
    ],
  },

  // ─── 09 - Benefits Enrollment ──────────────────────────────
  {
    formCode: "FR-09.01",
    name: "Benefits Enrollment Form",
    description: "Health insurance, dental, vision, life insurance, 401(k) selections.",
    binderArea: "09_Benefits_Enrollment",
    binderAreaIndex: 9,
    lifecycleModule: "benefits-enrollment",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "enrollmentDate", label: "Enrollment Date", fieldType: "date", required: true, section: "Header" },
      { name: "healthPlan", label: "Health Insurance Plan", fieldType: "select", required: true, options: ["PPO - Single", "PPO - Family", "HMO - Single", "HMO - Family", "Waived"], section: "Health" },
      { name: "dentalPlan", label: "Dental Plan", fieldType: "select", required: true, options: ["Basic", "Premium", "Waived"], section: "Dental" },
      { name: "visionPlan", label: "Vision Plan", fieldType: "select", required: true, options: ["Standard", "Enhanced", "Waived"], section: "Vision" },
      { name: "lifeInsurance", label: "Life Insurance Election", fieldType: "select", required: true, options: ["1x Salary", "2x Salary", "3x Salary", "Waived"], section: "Life" },
      { name: "disabilityInsurance", label: "Short-Term Disability", fieldType: "select", required: true, options: ["Enrolled", "Waived"], section: "Disability" },
      { name: "four01kEnrollment", label: "401(k) Enrollment", fieldType: "select", required: true, options: ["Enrolled", "Waived", "Deferred Decision"], section: "Retirement" },
      { name: "four01kContribution", label: "401(k) Contribution %", fieldType: "number", required: false, section: "Retirement" },
      { name: "beneficiaryName", label: "Primary Beneficiary", fieldType: "text", required: true, section: "Beneficiary" },
      { name: "beneficiaryRelationship", label: "Relationship", fieldType: "text", required: true, section: "Beneficiary" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "date", label: "Date", fieldType: "date", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:benefits-enrollment", dueDays: 30 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:benefits-enrollment", dueDays: 30 },
    ],
  },
  {
    formCode: "FR-09.02",
    name: "Beneficiary Designation Form",
    description: "Primary and contingent beneficiary designations for all benefits.",
    binderArea: "09_Benefits_Enrollment",
    binderAreaIndex: 9,
    lifecycleModule: "benefits-enrollment",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "primaryName", label: "Primary Beneficiary Name", fieldType: "text", required: true, section: "Primary" },
      { name: "primaryRelationship", label: "Relationship", fieldType: "text", required: true, section: "Primary" },
      { name: "primarySsn", label: "SSN", fieldType: "text", required: true, section: "Primary" },
      { name: "primaryShare", label: "Share %", fieldType: "number", required: true, section: "Primary" },
      { name: "contingentName", label: "Contingent Beneficiary Name", fieldType: "text", required: false, section: "Contingent" },
      { name: "contingentRelationship", label: "Relationship", fieldType: "text", required: false, section: "Contingent" },
      { name: "contingentShare", label: "Share %", fieldType: "number", required: false, section: "Contingent" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "date", label: "Date", fieldType: "date", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:benefits-enrollment", dueDays: 30 },
    ],
  },

  // ─── 10 - Performance ──────────────────────────────────────
  {
    formCode: "FR-10.01",
    name: "Probationary Review (30-Day)",
    description: "First probationary review at 30 days of employment.",
    binderArea: "10_Performance",
    binderAreaIndex: 10,
    lifecycleModule: "performance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "reviewDate", label: "Review Date", fieldType: "date", required: true, section: "Header" },
      { name: "periodStart", label: "Review Period Start", fieldType: "date", required: true, section: "Header" },
      { name: "periodEnd", label: "Review Period End", fieldType: "date", required: true, section: "Header" },
      { name: "attendanceRating", label: "Attendance & Punctuality", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "jobKnowledgeRating", label: "Job Knowledge", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "qualityRating", label: "Quality of Work", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "communicationRating", label: "Communication", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "teamworkRating", label: "Teamwork", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "overallRating", label: "Overall Rating", fieldType: "select", required: true, options: ["Exceeds Expectations", "Meets Expectations", "Needs Improvement", "Unsatisfactory"], section: "Summary" },
      { name: "supervisorComments", label: "Supervisor Comments", fieldType: "textarea", required: true, section: "Comments" },
      { name: "employeeComments", label: "Employee Comments", fieldType: "textarea", required: false, section: "Comments" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "hrSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 30 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 30 },
    ],
  },
  {
    formCode: "FR-10.02",
    name: "Probationary Review (90-Day)",
    description: "Final probationary review at 90 days.",
    binderArea: "10_Performance",
    binderAreaIndex: 10,
    lifecycleModule: "performance",
    requiredForGate: true,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "reviewDate", label: "Review Date", fieldType: "date", required: true, section: "Header" },
      { name: "periodStart", label: "Review Period Start", fieldType: "date", required: true, section: "Header" },
      { name: "periodEnd", label: "Review Period End", fieldType: "date", required: true, section: "Header" },
      { name: "attendanceRating", label: "Attendance & Punctuality", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "jobKnowledgeRating", label: "Job Knowledge", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "qualityRating", label: "Quality of Work", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "communicationRating", label: "Communication", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "teamworkRating", label: "Teamwork", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "documentationRating", label: "Documentation Quality", fieldType: "select", required: true, options: ["Exceeds", "Meets", "Needs Improvement", "Unsatisfactory"], section: "Ratings" },
      { name: "overallRating", label: "Overall Rating", fieldType: "select", required: true, options: ["Exceeds Expectations", "Meets Expectations", "Needs Improvement", "Unsatisfactory"], section: "Summary" },
      { name: "recommendation", label: "Recommendation", fieldType: "select", required: true, options: ["Convert to Regular Employment", "Extend Probation", "Terminate"], section: "Summary" },
      { name: "supervisorComments", label: "Supervisor Comments", fieldType: "textarea", required: true, section: "Comments" },
      { name: "employeeComments", label: "Employee Comments", fieldType: "textarea", required: false, section: "Comments" },
      { name: "actionItems", label: "Action Items / Development Plan", fieldType: "textarea", required: false, section: "Development" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "hrSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 90 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 90 },
    ],
  },
  {
    formCode: "FR-10.03",
    name: "Annual Performance Evaluation",
    description: "Comprehensive annual performance review.",
    binderArea: "10_Performance",
    binderAreaIndex: 10,
    lifecycleModule: "performance",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    renewalRule: "R5 - Renew Every 12 Months",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "reviewDate", label: "Review Date", fieldType: "date", required: true, section: "Header" },
      { name: "reviewPeriod", label: "Review Period", fieldType: "text", required: true, section: "Header" },
      { name: "goalsMet", label: "Prior Year Goals Met?", fieldType: "select", required: true, options: ["All", "Most", "Some", "None"], section: "Goals" },
      { name: "goalDetails", label: "Goal Achievement Details", fieldType: "textarea", required: true, section: "Goals" },
      { name: "newGoals", label: "New Year Goals", fieldType: "textarea", required: true, section: "Goals" },
      { name: "overallRating", label: "Overall Rating", fieldType: "select", required: true, options: ["Exceptional", "Exceeds Expectations", "Meets Expectations", "Needs Improvement", "Unsatisfactory"], section: "Summary" },
      { name: "salaryRecommendation", label: "Salary Recommendation", fieldType: "select", required: true, options: ["Merit Increase", "Standard Increase", "No Increase", "Reduction"], section: "Compensation" },
      { name: "promotionConsideration", label: "Promotion Consideration", fieldType: "select", required: true, options: ["Yes", "No", "Not Yet"], section: "Compensation" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "hrSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 365 },
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-status-change:offers-o-accepted", dueDays: 365 },
    ],
  },
  {
    formCode: "FR-10.04",
    name: "Corrective Action Form",
    description: "Documented progressive discipline.",
    binderArea: "10_Performance",
    binderAreaIndex: 10,
    lifecycleModule: "performance",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "incidentDate", label: "Date of Incident", fieldType: "date", required: true, section: "Incident" },
      { name: "incidentDescription", label: "Description of Incident", fieldType: "textarea", required: true, section: "Incident" },
      { name: "policyViolated", label: "Policy Violated", fieldType: "text", required: true, section: "Incident" },
      { name: "actionLevel", label: "Corrective Action Level", fieldType: "select", required: true, options: ["Verbal Warning", "Written Warning", "Final Written Warning", "Suspension", "Termination"], section: "Action" },
      { name: "expectedImprovement", label: "Expected Improvement", fieldType: "textarea", required: true, section: "Action" },
      { name: "followUpDate", label: "Follow-Up Review Date", fieldType: "date", required: true, section: "Follow-Up" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "hrSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
      { role: "hr-director", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
    ],
  },

  // ─── 11 - Separation ───────────────────────────────────────
  {
    formCode: "FR-11.01",
    name: "Voluntary Resignation Form",
    description: "Employee-initiated resignation with notice period.",
    binderArea: "11_Separation",
    binderAreaIndex: 11,
    lifecycleModule: "separation",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "lastDay", label: "Last Day of Work", fieldType: "date", required: true, section: "Resignation" },
      { name: "resignationDate", label: "Resignation Date", fieldType: "date", required: true, section: "Resignation" },
      { name: "reason", label: "Reason for Leaving", fieldType: "select", required: true, options: ["New Opportunity", "Relocation", "Personal Reasons", "Health", "Retirement", "Other"], section: "Resignation" },
      { name: "reasonDetails", label: "Details", fieldType: "textarea", required: false, section: "Resignation" },
      { name: "exitInterviewRequested", label: "Exit Interview Requested", fieldType: "checkbox", required: true, section: "Exit" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Acknowledgment", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "rcs-day", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:separation", dueDays: 1 },
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:separation", dueDays: 1 },
    ],
  },
  {
    formCode: "FR-11.02",
    name: "Exit Interview Form",
    description: "Structured exit interview questionnaire.",
    binderArea: "11_Separation",
    binderAreaIndex: 11,
    lifecycleModule: "separation",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "interviewDate", label: "Interview Date", fieldType: "date", required: true, section: "Header" },
      { name: "interviewer", label: "Interviewer", fieldType: "text", required: true, section: "Header" },
      { name: "reasonForLeaving", label: "Primary Reason for Leaving", fieldType: "select", required: true, options: ["Compensation", "Supervision", "Work Environment", "Career Growth", "Personal", "Terminated"], section: "Reasons" },
      { name: "satisfiedOverall", label: "Overall Satisfaction", fieldType: "select", required: true, options: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very Dissatisfied"], section: "Feedback" },
      { name: "wouldRecommend", label: "Would Recommend as Employer", fieldType: "select", required: true, options: ["Yes", "No", "Maybe"], section: "Feedback" },
      { name: "improvements", label: "Suggested Improvements", fieldType: "textarea", required: true, section: "Feedback" },
      { name: "returnEligible", label: "Eligible for Rehire", fieldType: "select", required: true, options: ["Yes", "No", "Conditional"], section: "Disposition" },
      { name: "interviewerSignature", label: "Interviewer Signature", fieldType: "signature", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:separation", dueDays: 7 },
    ],
  },
  {
    formCode: "FR-11.03",
    name: "Final Pay & Benefits Termination Checklist",
    description: "Tracks all final pay, benefits termination, and COBRA notifications.",
    binderArea: "11_Separation",
    binderAreaIndex: 11,
    lifecycleModule: "separation",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "lastDay", label: "Last Day", fieldType: "date", required: true, section: "Employee" },
      { name: "finalPaycheckDate", label: "Final Paycheck Date", fieldType: "date", required: true, section: "Payroll" },
      { name: "ptoPayout", label: "PTO Payout Calculated", fieldType: "checkbox", required: true, section: "Payroll" },
      { name: "healthTerminated", label: "Health Insurance Terminated", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "dentalTerminated", label: "Dental Insurance Terminated", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "visionTerminated", label: "Vision Insurance Terminated", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "cobraNoticeSent", label: "COBRA Notice Sent", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "cobraDateSent", label: "COBRA Notice Date", fieldType: "date", required: true, section: "Benefits" },
      { name: "lifeInsuranceTerminated", label: "Life Insurance Terminated", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "four01kOptions", label: "401(k) Distribution Options Provided", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "unemploymentInfo", label: "Unemployment Information Provided", fieldType: "checkbox", required: true, section: "Benefits" },
      { name: "hrDirectorSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "payrollSignature", label: "Payroll Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:separation", dueDays: 14 },
    ],
  },
  {
    formCode: "FR-11.04",
    name: "Equipment & Property Return Checklist",
    description: "Inventory of all company property to be returned.",
    binderArea: "11_Separation",
    binderAreaIndex: 11,
    lifecycleModule: "separation",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "buildingKeys", label: "Building Keys Returned", fieldType: "checkbox", required: true, section: "Items" },
      { name: "officeKeys", label: "Office Keys Returned", fieldType: "checkbox", required: true, section: "Items" },
      { name: "accessCard", label: "Access Card / Badge Returned", fieldType: "checkbox", required: true, section: "Items" },
      { name: "laptop", label: "Laptop / Tablet Returned", fieldType: "checkbox", required: true, section: "Items" },
      { name: "phone", label: "Company Phone Returned", fieldType: "checkbox", required: true, section: "Items" },
      { name: "uniform", label: "Uniform Returned", fieldType: "checkbox", required: true, section: "Items" },
      { name: "parkingPass", label: "Parking Pass Returned", fieldType: "checkbox", required: false, section: "Items" },
      { name: "otherItems", label: "Other Items", fieldType: "textarea", required: false, section: "Items" },
      { name: "damageNotes", label: "Damage / Missing Item Notes", fieldType: "textarea", required: false, section: "Notes" },
      { name: "employeeSignature", label: "Employee Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "supervisorSignature", label: "Supervisor Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:separation", dueDays: 1 },
    ],
  },
  {
    formCode: "FR-11.05",
    name: "Personnel File Archiving Form",
    description: "Certifies that the personnel file is complete and ready for archival.",
    binderArea: "11_Separation",
    binderAreaIndex: 11,
    lifecycleModule: "separation",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    retentionCategory: "C1 - Permanent",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "terminationDate", label: "Termination / Separation Date", fieldType: "date", required: true, section: "Header" },
      { name: "allSectionsComplete", label: "All Binder Sections Complete", fieldType: "checkbox", required: true, section: "Verification" },
      { name: "noMissingDocs", label: "No Missing Documents", fieldType: "checkbox", required: true, section: "Verification" },
      { name: "auditTrailComplete", label: "Audit Trail Complete", fieldType: "checkbox", required: true, section: "Verification" },
      { name: "fileSentToArchive", label: "File Sent to Archive", fieldType: "checkbox", required: true, section: "Archival" },
      { name: "archiveDate", label: "Archive Date", fieldType: "date", required: true, section: "Archival" },
      { name: "archiveLocation", label: "Archive Location / Box #", fieldType: "text", required: true, section: "Archival" },
      { name: "retentionPeriod", label: "Retention Period", fieldType: "select", required: true, options: ["7 Years", "Permanent", "Other"], section: "Archival" },
      { name: "hrDirectorSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "archivistSignature", label: "Archivist Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: true, isAutoAssigned: true, assignmentTrigger: "on-module-entry:separation", dueDays: 30 },
    ],
  },

  // ─── 12 - Grievance & Compliance ───────────────────────────
  {
    formCode: "FR-12.01",
    name: "Incident Report Form",
    description: "Standard incident report for any workplace event.",
    binderArea: "12_Grievance_Compliance",
    binderAreaIndex: 12,
    lifecycleModule: "grievance-compliance",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "reporterName", label: "Person Completing Report", fieldType: "text", required: true, section: "Reporter" },
      { name: "reporterTitle", label: "Title", fieldType: "text", required: true, section: "Reporter" },
      { name: "incidentDate", label: "Date of Incident", fieldType: "date", required: true, section: "Incident" },
      { name: "incidentTime", label: "Time of Incident", fieldType: "text", required: true, section: "Incident" },
      { name: "location", label: "Location", fieldType: "text", required: true, section: "Incident" },
      { name: "individualsInvolved", label: "Individuals Involved", fieldType: "textarea", required: true, section: "Incident" },
      { name: "incidentDescription", label: "Detailed Description", fieldType: "textarea", required: true, section: "Description" },
      { name: "immediateAction", label: "Immediate Action Taken", fieldType: "textarea", required: true, section: "Action" },
      { name: "witnesses", label: "Witnesses", fieldType: "textarea", required: false, section: "Witnesses" },
      { name: "followUpRequired", label: "Follow-Up Required", fieldType: "checkbox", required: true, section: "Follow-Up" },
      { name: "reporterSignature", label: "Reporter Signature", fieldType: "signature", required: true, section: "Signature" },
      { name: "supervisorSignature", label: "Supervisor Review Signature", fieldType: "signature", required: true, section: "Signature" },
    ],
    roleBindings: [
      { role: "shift-supervisor", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
    ],
  },

  // ─── 13 - File Management ──────────────────────────────────
  {
    formCode: "FR-13.01",
    name: "Personnel File Transfer Log",
    description: "Tracks any movement or transfer of the personnel file.",
    binderArea: "13_File_Management",
    binderAreaIndex: 13,
    lifecycleModule: "file-management",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: false,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "transferDate", label: "Transfer Date", fieldType: "date", required: true, section: "Transfer" },
      { name: "fromLocation", label: "From Location", fieldType: "text", required: true, section: "Transfer" },
      { name: "toLocation", label: "To Location", fieldType: "text", required: true, section: "Transfer" },
      { name: "reason", label: "Reason for Transfer", fieldType: "textarea", required: true, section: "Transfer" },
      { name: "transferredBy", label: "Transferred By", fieldType: "text", required: true, section: "Transfer" },
      { name: "receivedBy", label: "Received By", fieldType: "text", required: true, section: "Transfer" },
      { name: "transferredBySignature", label: "Transferred By Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "receivedBySignature", label: "Received By Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "hr-director", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
    ],
  },

  // ─── 14 - Audit Logs ───────────────────────────────────────
  {
    formCode: "FR-14.01",
    name: "HR Binder Audit Log",
    description: "Quarterly audit log confirming completeness and accuracy of the HR binder.",
    binderArea: "14_Audit_Logs",
    binderAreaIndex: 14,
    lifecycleModule: "audit-logs",
    requiredForGate: false,
    signatureRequired: true,
    reviewerRequired: true,
    outputFormat: "pdf",
    fields: [
      { name: "employeeName", label: "Employee Name", fieldType: "text", required: true, section: "Employee" },
      { name: "employeeId", label: "Employee ID", fieldType: "text", required: true, section: "Employee" },
      { name: "auditDate", label: "Audit Date", fieldType: "date", required: true, section: "Audit" },
      { name: "auditorName", label: "Auditor Name / Title", fieldType: "text", required: true, section: "Audit" },
      { name: "sectionsAudited", label: "Sections Audited", fieldType: "multiselect", required: true, options: ["01 Recruitment", "02 Conditional Offer", "03 Pre-Employment", "04 Screening", "05 Final Agreement", "06 Orientation", "07 Training", "08 GRO Assignment", "09 Benefits", "10 Performance", "11 Separation"], section: "Audit" },
      { name: "allFormsPresent", label: "All Required Forms Present", fieldType: "checkbox", required: true, section: "Findings" },
      { name: "allSignaturesPresent", label: "All Signatures Present", fieldType: "checkbox", required: true, section: "Findings" },
      { name: "missingItems", label: "Missing Items (if any)", fieldType: "textarea", required: false, section: "Findings" },
      { name: "correctiveActions", label: "Corrective Actions", fieldType: "textarea", required: false, section: "Corrective" },
      { name: "nextAuditDate", label: "Next Audit Date", fieldType: "date", required: true, section: "Follow-Up" },
      { name: "auditorSignature", label: "Auditor Signature", fieldType: "signature", required: true, section: "Signatures" },
      { name: "hrDirectorSignature", label: "HR Director Signature", fieldType: "signature", required: true, section: "Signatures" },
    ],
    roleBindings: [
      { role: "hr-compliance-officer", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
      { role: "hr-director", isRequired: false, isAutoAssigned: false, assignmentTrigger: "manual", dueDays: 0 },
    ],
  },
];

// ─── Seed Function ───────────────────────────────────────────

async function seed() {
  console.log("Seeding Forms Registry...\n");

  for (const form of FORMS) {
    const templateId = randomUUID();

    // Insert template
    await db.insert(formTemplates).values({
      id: templateId,
      formCode: form.formCode,
      name: form.name,
      description: form.description ?? null,
      binderArea: form.binderArea,
      binderAreaIndex: form.binderAreaIndex,
      lifecycleModule: form.lifecycleModule ?? null,
      requiredForGate: form.requiredForGate,
      signatureRequired: form.signatureRequired,
      reviewerRequired: form.reviewerRequired,
      outputFormat: form.outputFormat,
      retentionCategory: form.retentionCategory ?? null,
      renewalRule: form.renewalRule ?? null,
      sortOrder: parseInt(form.formCode.split(".")[1]) || 0,
    });

    // Insert fields
    for (const field of form.fields) {
      await db.insert(formTemplateFields).values({
        id: randomUUID(),
        templateId,
        name: field.name,
        label: field.label,
        fieldType: field.fieldType,
        required: field.required,
        optionsJson: field.options ? JSON.stringify(field.options) : null,
        section: field.section ?? null,
        sortOrder: form.fields.indexOf(field),
      });
    }

    // Insert role bindings
    for (const binding of form.roleBindings) {
      await db.insert(formRoleBindings).values({
        id: randomUUID(),
        templateId,
        role: binding.role,
        isRequired: binding.isRequired,
        isAutoAssigned: binding.isAutoAssigned,
        assignmentTrigger: binding.assignmentTrigger,
        dueDays: binding.dueDays,
      });
    }

    console.log(`  ${form.formCode} — ${form.name} (${form.fields.length} fields, ${form.roleBindings.length} bindings)`);
  }

  console.log(`\nSeeded ${FORMS.length} form templates.`);
  console.log("Done!");

  client.close();
}

seed().catch(console.error);
