/**
 * Fictional M2.1 evaluation fixtures.
 *
 * These aliases and identifiers are intentionally synthetic. They must never be
 * represented as production evidence or merged into operational records.
 */

const SYNTHETIC_LABEL =
  "Fictional synthetic preview — not production evidence or a live caseload";

const queueItems = {
  intake: [
    {
      id: "SYN-WI-INT-001",
      caseId: "SYN-CASE-ATLAS",
      referralId: "SYN-REF-ATLAS",
      youthDisplayLabel: "Youth Atlas (fictional)",
      title: "Eligibility evidence review",
      status: "in_review",
      priority: "urgent",
      assignedDepartment: "ccmg",
      assignedRole: "intake-coordinator",
      assignedTo: "Synthetic Intake Desk",
      dueAt: "2026-07-14T16:00:00.000Z",
      overdue: false,
      approvalStatus: "pending",
      exceptionCode: "ELIGIBILITY_SOURCE_PENDING",
      updatedAt: "2026-07-14T13:20:00.000Z",
    },
    {
      id: "SYN-WI-INT-002",
      caseId: "SYN-CASE-BIRCH",
      referralId: "SYN-REF-BIRCH",
      youthDisplayLabel: "Youth Birch (fictional)",
      title: "Guardian consent follow-up",
      status: "blocked",
      priority: "high",
      assignedDepartment: "ccmg",
      assignedRole: "bhc-front-desk",
      assignedTo: "Synthetic Access Team",
      dueAt: "2026-07-13T18:00:00.000Z",
      overdue: true,
      approvalStatus: "not_required",
      exceptionCode: "CONSENT_INCOMPLETE",
      updatedAt: "2026-07-14T11:05:00.000Z",
    },
  ],
  qa: [
    {
      id: "SYN-WI-QA-001",
      caseId: "SYN-CASE-CEDAR",
      referralId: "SYN-REF-CEDAR",
      youthDisplayLabel: "Youth Cedar (fictional)",
      title: "Corrective documentation review",
      status: "open_finding",
      priority: "high",
      assignedDepartment: "ccmg",
      assignedRole: "chart-auditor",
      assignedTo: "Synthetic QA Reviewer",
      dueAt: "2026-07-15T17:00:00.000Z",
      overdue: false,
      approvalStatus: "pending",
      exceptionCode: "SIGNATURE_SEQUENCE",
      updatedAt: "2026-07-14T12:10:00.000Z",
    },
  ],
  cans: [
    {
      id: "SYN-WI-CANS-001",
      caseId: "SYN-CASE-DELTA",
      referralId: "SYN-REF-DELTA",
      youthDisplayLabel: "Youth Delta (fictional)",
      title: "CANS reassessment due",
      status: "due",
      priority: "urgent",
      assignedDepartment: "ccmg",
      assignedRole: "qmhp-cs",
      assignedTo: "Synthetic QMHP Queue",
      dueAt: "2026-07-14T20:00:00.000Z",
      overdue: false,
      approvalStatus: "not_required",
      exceptionCode: null,
      updatedAt: "2026-07-14T10:40:00.000Z",
    },
  ],
  medication_management: [
    {
      id: "SYN-WI-MED-001",
      caseId: "SYN-CASE-EMBER",
      referralId: "SYN-REF-EMBER",
      youthDisplayLabel: "Youth Ember (fictional)",
      title: "Medication follow-up coordination",
      status: "awaiting_handoff",
      priority: "high",
      assignedDepartment: "ccmg",
      assignedRole: "nurse",
      assignedTo: "Synthetic Nursing Queue",
      dueAt: "2026-07-14T15:30:00.000Z",
      overdue: false,
      approvalStatus: "pending",
      exceptionCode: "FOLLOW_UP_WINDOW",
      updatedAt: "2026-07-14T13:45:00.000Z",
    },
  ],
  mhtcm: [
    {
      id: "SYN-WI-TCM-001",
      caseId: "SYN-CASE-FERN",
      referralId: "SYN-REF-FERN",
      youthDisplayLabel: "Youth Fern (fictional)",
      title: "Care-plan coordination contact",
      status: "overdue",
      priority: "standard",
      assignedDepartment: "mhtcm",
      assignedRole: "case-manager",
      assignedTo: "Synthetic MHTCM Queue",
      dueAt: "2026-07-12T17:00:00.000Z",
      overdue: true,
      approvalStatus: "not_required",
      exceptionCode: "CONTACT_ATTEMPT_DUE",
      updatedAt: "2026-07-13T19:00:00.000Z",
    },
  ],
  mhrs: [
    {
      id: "SYN-WI-RS-001",
      caseId: "SYN-CASE-GROVE",
      referralId: "SYN-REF-GROVE",
      youthDisplayLabel: "Youth Grove (fictional)",
      title: "Service-start readiness check",
      status: "ready_for_approval",
      priority: "high",
      assignedDepartment: "mhrs",
      assignedRole: "mhrs-supervisor",
      assignedTo: "Synthetic MHRS Queue",
      dueAt: "2026-07-15T16:00:00.000Z",
      overdue: false,
      approvalStatus: "pending",
      exceptionCode: null,
      updatedAt: "2026-07-14T09:15:00.000Z",
    },
  ],
} as const;

export const CCMG_SYNTHETIC_DASHBOARD = {
  generatedAt: "2026-07-14T14:00:00.000Z",
  evidenceClass: "synthetic_demo" as const,
  evidenceLabel: SYNTHETIC_LABEL,
  actor: {
    id: "synthetic-evaluation-viewer",
    role: "Synthetic evaluation context",
    visibleQueueIds: [
      "intake",
      "qa",
      "cans",
      "medication_management",
      "mhtcm",
      "mhrs",
    ],
  },
  metrics: {
    totalReferrals: 18,
    openReferrals: 13,
    urgentReferrals: 4,
    heldReferrals: 2,
    overdueWorkItems: 3,
    pendingApprovals: 4,
    openExceptions: 5,
    activeHandoffs: 3,
    authorizationsPending: 4,
    cansDue: 3,
    highAcuityCases: 4,
    backlogWorkItems: 7,
    qaFindings: 1,
    serviceCoordinationItems: 2,
  },
  queues: [
    {
      id: "intake",
      label: "Intake",
      visible: true,
      total: 4,
      overdue: 1,
      urgent: 2,
      awaitingApproval: 1,
      blocked: 1,
      items: queueItems.intake,
    },
    {
      id: "qa",
      label: "QA findings",
      visible: true,
      total: 3,
      overdue: 0,
      urgent: 1,
      awaitingApproval: 1,
      blocked: 0,
      items: queueItems.qa,
    },
    {
      id: "cans",
      label: "CANS",
      visible: true,
      total: 3,
      overdue: 0,
      urgent: 1,
      awaitingApproval: 0,
      blocked: 0,
      items: queueItems.cans,
    },
    {
      id: "medication_management",
      label: "Medication oversight",
      visible: true,
      total: 2,
      overdue: 0,
      urgent: 1,
      awaitingApproval: 1,
      blocked: 0,
      items: queueItems.medication_management,
    },
    {
      id: "mhtcm",
      label: "MHTCM",
      visible: true,
      total: 3,
      overdue: 2,
      urgent: 0,
      awaitingApproval: 0,
      blocked: 1,
      items: queueItems.mhtcm,
    },
    {
      id: "mhrs",
      label: "MHRS",
      visible: true,
      total: 3,
      overdue: 0,
      urgent: 1,
      awaitingApproval: 1,
      blocked: 0,
      items: queueItems.mhrs,
    },
  ],
  audit: {
    accessEventId: "SYN-AUD-ACCESS-001",
    loggedAt: "2026-07-14T14:00:00.000Z",
  },
};

export function getSyntheticCcmgReferralDetail(referralId: string) {
  const queueItem = Object.values(queueItems)
    .flat()
    .find((item) => item.referralId === referralId);
  const selected = queueItem ?? queueItems.intake[0];

  return {
    evidenceClass: "synthetic_demo" as const,
    evidenceLabel: SYNTHETIC_LABEL,
    referral: {
      id: selected.referralId,
      caseId: selected.caseId,
      evidenceClass: "synthetic_demo" as const,
      youthId: `SYN-YOUTH-${selected.referralId.replace("SYN-REF-", "")}`,
      youthDisplayLabel: selected.youthDisplayLabel,
      referralSourceDivision: "Fictional community source",
      referredAt: "2026-07-10T15:30:00.000Z",
      referralReason:
        "Synthetic care-coordination scenario for acceptance review.",
      urgency: selected.priority,
      status: selected.status,
      holdReason: selected.status === "blocked" ? selected.exceptionCode : null,
      rejectionReason: null,
      createdAt: "2026-07-10T15:30:00.000Z",
      updatedAt: selected.updatedAt,
      version: 3,
      authorizationStatus: "pending_review",
    },
    coordinationSummary:
      "Fictional cross-program handoff is awaiting confirmation from the next assigned service queue.",
    gates: {
      intake: {
        status: "complete",
        detail: "Synthetic intake packet logged.",
        ownerRole: "intake-coordinator",
        updatedAt: "2026-07-10T16:00:00.000Z",
      },
      eligibility: {
        status: "verified",
        detail: "Fictional eligibility evidence checked.",
        ownerRole: "intake-coordinator",
        updatedAt: "2026-07-11T14:00:00.000Z",
      },
      payerAuthorization: {
        status: "pending",
        detail: "Synthetic payer response expected within the demo window.",
        ownerRole: "ccmg-program-director",
        updatedAt: "2026-07-14T12:00:00.000Z",
      },
      consent: {
        status: "complete",
        detail: "Fictional consent verification recorded.",
        ownerRole: "bhc-front-desk",
        updatedAt: "2026-07-11T16:10:00.000Z",
      },
      cans: {
        status: "current",
        detail: "Synthetic CANS v2 is current for routing review.",
        ownerRole: "qmhp-cs",
        updatedAt: "2026-07-13T18:30:00.000Z",
      },
      capacity: {
        status: "conditional",
        detail: "Fictional capacity held pending authorization.",
        ownerRole: "ccmg-program-director",
        updatedAt: "2026-07-14T13:00:00.000Z",
      },
      readiness: {
        ready: false,
        status: "blocked",
        gates: ["payerAuthorization"],
        reasonCodes: ["AUTHORIZATION_PENDING"],
        evaluatedAt: "2026-07-14T13:05:00.000Z",
      },
    },
    workflow: {
      assignments: [
        {
          id: "SYN-ASN-003",
          workItemId: selected.id,
          assignedDivision: "BHC",
          assignedDepartment: selected.assignedDepartment.toUpperCase(),
          assignedRole: selected.assignedRole,
          assignedTo: selected.assignedTo,
          dueAt: selected.dueAt,
          status: "active",
          escalationLevel: "none",
          exceptionCode: selected.exceptionCode,
          exceptionStatus: selected.exceptionCode ? "open" : "none",
          version: 3,
          assignedAt: "2026-07-14T09:00:00.000Z",
        },
      ],
      approvals: [
        {
          id: "SYN-APR-001",
          workItemId: selected.id,
          status: selected.approvalStatus,
          requestedRole: "ccmg-program-director",
          requestedAt: "2026-07-14T10:00:00.000Z",
        },
      ],
      exceptions: selected.exceptionCode
        ? [
            {
              id: "SYN-EXC-001",
              code: selected.exceptionCode,
              status: "open",
              detail: "Fictional exception requiring oversight review.",
            },
          ]
        : [],
      handoffs: [
        {
          id: "SYN-HO-001",
          status: "pending",
          toDivision: "bhc",
          toDepartment: "mhtcm",
          dueAt: "2026-07-15T17:00:00.000Z",
          reason: "Fictional coordination handoff pending acknowledgement.",
          version: 1,
        },
      ],
    },
    cansLineage: {
      versions: [
        {
          id: "SYN-CANS-ATLAS-V2",
          version: "v2",
          instrumentVersion: "CANS 2.0",
          completedAt: "2026-07-13T18:30:00.000Z",
          completedByRole: "qmhp-cs",
          totalScore: 28,
          riskLevel: "high",
          source: "Synthetic assessment fixture",
          supersedes: "SYN-CANS-ATLAS-V1",
        },
        {
          id: "SYN-CANS-ATLAS-V1",
          version: "v1",
          instrumentVersion: "CANS 2.0",
          completedAt: "2026-06-13T17:00:00.000Z",
          completedByRole: "qmhp-cs",
          totalScore: 22,
          riskLevel: "moderate",
          source: "Synthetic assessment fixture",
          supersedes: null,
        },
      ],
      routes: [
        {
          assessmentId: "SYN-CANS-ATLAS-V2",
          targetType: "mhtcm_plan",
          targetRecordId: "SYN-MHTCM-PLAN-ATLAS-V2",
          targetVersion: 2,
          targetApprovalStatus: "approved",
          routedAt: "2026-07-13T19:00:00.000Z",
          routedBy: "synthetic-routing-service",
          mappedGoals: [{ goalCode: "SYN-MHTCM-GOAL-1" }],
          reason: "Synthetic high-acuity routing rule.",
        },
        {
          assessmentId: "SYN-CANS-ATLAS-V2",
          targetType: "mhrs_skills_goals",
          targetRecordId: "SYN-MHRS-GOALS-ATLAS-V2",
          targetVersion: 3,
          targetApprovalStatus: "approved",
          routedAt: "2026-07-13T19:00:00.000Z",
          routedBy: "synthetic-routing-service",
          mappedGoals: [
            { goalCode: "SYN-MHRS-GOAL-1" },
            { goalCode: "SYN-MHRS-GOAL-2" },
          ],
          reason: "Synthetic skills-routing rule.",
        },
        {
          assessmentId: "SYN-CANS-ATLAS-V1",
          targetType: "mhtcm_plan",
          targetRecordId: "SYN-MHTCM-PLAN-ATLAS-V1",
          targetVersion: 1,
          targetApprovalStatus: "approved",
          mappedGoals: [{ goalCode: "SYN-MHTCM-GOAL-INITIAL" }],
          reason: "Synthetic initial routing rule.",
        },
        {
          assessmentId: "SYN-CANS-ATLAS-V1",
          targetType: "mhrs_skills_goals",
          targetRecordId: "SYN-MHRS-GOALS-ATLAS-V1",
          targetVersion: 1,
          targetApprovalStatus: "approved",
          mappedGoals: [{ goalCode: "SYN-MHRS-GOAL-INITIAL" }],
          reason: "Synthetic initial skills-routing rule.",
        },
      ],
    },
    audit: {
      accessEventId: "SYN-AUD-ACCESS-DETAIL-001",
      events: [
        {
          id: "SYN-AUD-004",
          occurredAt: "2026-07-14T13:20:00.000Z",
          actorRole: "ccmg-program-director",
          action: "Readiness evaluated",
          detail:
            "Authorization gate remains pending; capacity is conditional.",
          source: "Synthetic workflow fixture",
        },
        {
          id: "SYN-AUD-003",
          occurredAt: "2026-07-14T10:00:00.000Z",
          actorRole: "intake-coordinator",
          action: "Approval requested",
          detail: "Fictional review routed to CCMG program oversight.",
          source: "Synthetic workflow fixture",
        },
        {
          id: "SYN-AUD-002",
          occurredAt: "2026-07-13T18:30:00.000Z",
          actorRole: "qmhp-cs",
          action: "CANS v2 completed",
          detail: "Synthetic lineage preserved from v1 to v2.",
          source: "Synthetic assessment fixture",
        },
        {
          id: "SYN-AUD-001",
          occurredAt: "2026-07-10T15:30:00.000Z",
          actorRole: "intake-coordinator",
          action: "Referral created",
          detail: "Fictional referral entered for M2.1 acceptance review.",
          source: "Synthetic intake fixture",
        },
      ],
    },
  };
}
